### ISSUE TITLE
`spiced` cannot be built with optional connectors

### ISSUE THREAD

**Issue by ahirner** [spiceai/spiceai#1025]
**Describe the bug**

One cannot build `spicedb` without `duckdb`. Firstly, top-level featurse are missing in `bin/spicedb/Cargo.toml`. Also, specifying workspace crate features, e.g. `"db_connection_pool/postgres"` doesn't control optional code and deps sufficiently.

**To Reproduce**

`cargo build --no-default-features --features "sqlite"` still includes `duckdb` and its sys crate.

**Expected behavior**

All of those run `spiced` with the requested connector support only:

`cargo run --no-default-features --features "sqlite"`
`cargo run --no-default-features --features "postgres"`
`cargo run --no-default-features --features "duckdb"`

Obviously any combintation should work too. The default features of `spicedb` shouldn't change.

**Additional context**

Some dependencies are heavy, in terms of build, platform and size requirements.
Going forward with #999 and #1000 aggrevates missing or not working top-level features.

I can work on that issue.

**Comment by phillipleblanc** [comment]
Thank you for reporting and fixing this issue - this is now merged!
