### ISSUE TITLE
[Delta Lake Direct] Dataset in Databricks configured with Liquid Clustering returning no results when querying with no limit

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1033]
**Describe the bug**
Reported in Discord:

I am trying to query data in Databricks via Spice, and got it to return data when using a limit. However, when I use a where clause I am getting errors. I am also running my machine out of RAM when I attempt to setup acceliration. The dataset I am testing on is a sync of data from Maxmind, where every IP address has a record. The query and error are:

sql> select * from table_name_here where ip = '104.63.88.72';
Error An internal error occurred while processing the query. Show technical details with '.error'
No data returned for query
sql> .error
Status { code: Internal, message: "Arrow error: External error: Parquet error: ParquetObjectReader::get_byte_ranges error: Generic S3 error: request or response body error: operation timed out", source: None }

Using a 200 file, 45.6 GiB dataset on Databricks with liquid clustering enabled.

Using acceleration in-memory leads to OOM error.  File based does sqlite or duckdb also doesn't succeed.

**Comment by ablyler** [comment]
Also, the query above would return a single row based on the data in the table.

**Comment by y-f-u** [comment]
@ablyler did you consistently getting the S3 generic error with where clause?

Underneath we are using delta-rs, so this issue might be related: https://github.com/delta-io/delta-rs/issues/2301.

I am going to test against our own databricks with similar data volume to see if it can reproduced.

**Comment by ablyler** [comment]
@y-f-u yes, it happens consistently. Exposing the timeout setting is a great idea!

**Comment by Sevenannn** [comment]
@ablyler Thanks again for reporting this issue! 

I’ve investigated and couldn’t reproduce it using the latest version (v1.0.0-rc.1). Could you help confirm if it’s still occurring on your end? If it’s resolved, we’d like to close this issue. Please let us know if you’re still encountering any problems, thanks!

**Comment by ablyler** [comment]
I am not sure, I don't have this environment set up at the moment. I say go ahead and close it and we can reopen if it happens again.

**Comment by Sevenannn** [comment]
@ablyler Sounds great! I’ll go ahead and close this issue for now. Please let us know if the same issue happens in the future. Thanks again!
