### ISSUE TITLE
[Delta Lake Direct] Query on a large databricks dataset (hundreds G) returns nothing

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#1035]
**Describe the bug**
Query on a large databricks dataset (hundreds G) returns nothing

**To Reproduce**
- ask @y-f-u for databricks dataset details
- include the dataset in spicepod
- spice run, the dataset should be loaded
- spice sql
- select * from dataset
- no result is returned, and query finished immediately

**Comment by Sevenannn** [comment]
Evaluated at the following version, with a 160GB+ data being queried from Databricks using delta mode, this issue cannot be reproduced. Therefore mark as closed
```
CLI version:     v1.0.0-rc.2-build.63fd16ff
Runtime version: v1.0.0-rc.2-build.63fd16ff
```
