### ISSUE TITLE
Enhancement: Trigger manual refresh API

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1057]
## Goal-State/What/Result

A `POST /v1/datasets/[name]/refresh` API for triggering manual refreshes from external applications.
 - The payload could contain additional refresh filters, like a specific Parquet file in the bucket for S3, or a time-range filter for time-series data.
 - Some safety machinery around refreshes to ensure duplicate/concurrent refreshes, don't happen, a good default of minimum refresh interval per source, etc. 
 - Data rate-limiting options for refreshes. 
 - Fuzzy Refresh: If many instances of Spice are refreshing at once, how do we ensure they all don't DDOS the source. Consider adding fuzziness to the refresh schedule.

Milestones:

M1: Basic dataset refresh
M2: Rate-Limited/Fuzzy Refresh. Moved to separate enhancement: https://github.com/spiceai/spiceai/issues/1102
M3: Filtered refresh. Moved to separate enhancement: https://github.com/spiceai/spiceai/issues/1102

## Why/Purpose

This is important for scenarios when very granular control over when data is refreshed is required:
 - have large dataset so would like to reduce unnecessary refreshes, data transfer over the network and associated cost
 - event based refreshes (for example, when source dataset has been updated)
 - when refresh schedule is hard to define using `refresh_interval`

For example, the team creates a reporting based on data queries every day at 8am. Instead of setting refresh interval for 1 hr to have fresh data I can create simple automation to trigger refresh via Api at 7-30am.

## By When

**Issue/Spec written and reviewed:** 04/10 (M1)

**M1:** 04/11
**M2 / M3:** Moved to separate enhancement: https://github.com/spiceai/spiceai/issues/1102
**Done-Done:** 04/17

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

**M1. Basic dataset refresh**

- `POST /v1/datasets/[name]/refresh` endpoint. 
  - Empty request body
  - Returns 201 when refresh has been successfully triggered
   ```json
  {
    "message": "Dataset refresh triggered for [name]"
  }
  ```
Following the algorithm (simplify, delete any part you can), moving this functionality out of basic implementation to https://github.com/spiceai/spiceai/issues/1102

  - ~~Returns 200 with message below if dataset refresh is already in progress.~~ 
   ```json
  {
    "message": "Refresh is already in progress for dataset [name]"
  }
  ```

## How/MAP

A clear and concise plan of how this should be implemented.

M1: Basic dataset refresh
 - [x] Update `AcceleratedTable` implementation to enable manual refreshes
 - [x] Add POST Api endpoint `v1/datasets/:name/refresh` to handle refresh
 - [x] Documentation update

### Implementation (issues)

- https://github.com/spiceai/spiceai/pull/1083
- https://github.com/spiceai/spiceai/pull/1078
- https://github.com/spiceai/spiceai/pull/1075
- https://github.com/spiceai/docs/pull/191

**Comment by sgrebnov** [comment]
Adding as potential ideas what could be in scope

Api endpoint to get refreshes history + example of PowerBI refresh request body
https://learn.microsoft.com/en-us/rest/api/power-bi/datasets/refresh-dataset

- `GET /v1/datasets/[name]/refreshes` endpoint. 
```
{ "value":[
  {
    "id":252103441,
    "refreshType":"Scheduled",
    "startTime":"2017-06-16T08:02:05.69Z",
    "endTime":"2017-06-16T08:14:29.61Z",
    "status":"Completed"
  },
  {
    "id":251845601,
    "refreshType":"ViaApi",
    "startTime":"2017-06-16T00:10:46.087Z",
    "endTime":"2017-06-16T00:10:53.04Z",
    "status":"Completed"
  },
// and etc…
} 
```

```
{
  "type": "full",
  "commitMode": "transactional",
  "objects": [
    {
      "table": "Customer",
      "partition": "Robert"
    }
  ],
  "applyRefreshPolicy": "false"
}
```

Will be great to have corresponding telemetry support (meta - dataset name , refreshType - `scheduled`, `viaApi`, etc):
  - `dataset_refresh_triggered`
  - `dataset_refresh_duration_ms`
  - `dataset_refresh_completed`
  - `dataset_refresh_failed`

**Comment by sgrebnov** [comment]
Basic functionality for manual refresh API has been implemented; created separate enhancement for advanced functionality (Rate-Limited/Fuzzy Refresh): https://github.com/spiceai/spiceai/issues/1102
