### ISSUE TITLE
Duckdb Data Connector

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#1062]
## Goal-State/What/Result

Spice OSS users can access persistent duckdb through the Spice runtime.

**Updates April 11th:**
MotherDuck relies on older version (0.9.2) of DuckDB, which causes issues including missing DuckDB data type, arrow - duckdb::arrow conversion, r2d2 DuckDB compatibility in other parts of the code. Since MotherDuck connector is based on a DuckDB connector, we redefine the milestones to start with implementing a DuckDB connector.

M1: Implement DuckDB data connector (using the version we use now 0.10.1).
M2: Pass E2E test For DuckDB Data Connector.
M3: DuckDB Data Connector Documentations & Customer Notified.

## Why/Purpose

Users of Spice that have data in DuckDB can query their data alongside other data sources through the spice runtime.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** April 9th

- [x] **M1:** April 10th
- [x] **M2:** April 15th
- [x] **M3:** April 15th

**Done-Done:** April 15th

## Done-Done

- [x] The Algorithm
- [x] First-Principles Driven
- [x] Issue reviewed by PM (Luke or Aurash)
- [x] Threat Model / Security Review
- [x] Tests (if applicable)
- [x] Dev
  - [x] Tested
  - [x] Qualitative & Performative Observability (Metrics & Dashboards)
  - [x] Alerting
- [x] Documentation
- [x] Customers notified (if applicable)

### User configuration in spicepod.yaml spec
```yaml
datasets:
  - from: duckdb:database.schema.table
    name: my_dataset
    params:
      open: path/to/duckdb_file.duckdb
```

## The Algorithm
- [x] Every requirement questioned?
  - [x] Duckdb rust library might not support attachment to MotherDuck
  - [x] Should MotherDuck connector be optional when runtime starts?
  - [x] How to shut down MotherDuck connection when not needed. 
- [x] Delete (Scope) any part you can.
  - [x] Duckdb connector, which could be relevant, should be supported in a separate enhancement ticket in the future
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automatatin.

**Comment by digadeesh** [comment]
I think the mode: file doesn't makes sense in this case.  There isn't any other option for their data connector.  We'll just have data file based data connectors.
