### ISSUE TITLE
"NULL" values not handled in postgres and mysql

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#1066]
**Describe the bug**

Spice runtime fails to load postgres and mysql datasets (probably other data sources as well) with null values

**Expected behavior**

Spice should properly load data with null values

**Screenshots**

![CleanShot 2024-04-10 at 18 02 15@2x](https://github.com/spiceai/spiceai/assets/827338/09a58bbb-ef6b-45d5-a4c6-ddda9a8dd9a3)

![CleanShot 2024-04-10 at 18 05 00@2x](https://github.com/spiceai/spiceai/assets/827338/90d64f3c-91c9-4be7-8aab-49b4b4e6ad37)

**Comment by digadeesh** [comment]
Fixed in: https://github.com/spiceai/spiceai/pull/1067
