### ISSUE TITLE
Manual refresh CLI command: `spice refresh [dataset-name]`

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1095]
## Goal-State/What/Result

Spice CLI includes command to trigger dataset refresh.

## Why/Purpose

We expose API to trigger dataset refresh but it requires additional knowledge of API signature and Spice runtime endpoint url. Adding cli command to initiate dataset refresh is important to have great developers experience.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** 04/15
**Done-Done:** 04/15

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] ~~Samples/Quickstarts/Tutorials~~ (not applicable)

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

1. Command signature:` spice refresh dataset-name`
1. `dataset-name` param is required. CLI should provide user friendly message with example usage when it is not provided
1. Command performs `/v1/datasets/dataset-name/refresh` POST request and prints `response.message` (API response JSON).
 - No need to process each HTTP response code separately (404, etc) as `response.message` contains user friendly information on execution result

## How/MAP
- [x] https://github.com/spiceai/spiceai/pull/1112
- [x] Document `spice refresh` command
- [x] Add `spice refresh` to E2E tests

### Implementation (issues)
- https://github.com/spiceai/spiceai/pull/1112
- https://github.com/spiceai/docs/pull/200
- https://github.com/spiceai/spiceai/pull/1125

**Comment by lukekim** [comment]
Issue needs completing with PM sign off.

**Comment by sgrebnov** [comment]
Implemented, documented, tests added
