### ISSUE TITLE
Error when upgrading Spice on Windows

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1144]
**Describe the bug**
When I run `spice upgrade` on Windows I see the `Error upgrading the spice binary:` error

```bash
PS C:\spice\test-app> spice upgrade
Checking for latest Spice CLI release...
Upgrading the Spice.ai CLI ...
Error upgrading the spice binary: rename C:\Users\sg\.spice\bin\66216e44\spice.exe C:\Users\sg\.spice\bin\spice.exe: Access is denied.
```

**To Reproduce**
1. Install Spice on Windows: `curl -L "https://install.spiceai.org/Install.ps1" -o Install.ps1 && PowerShell -ExecutionPolicy Bypass -File ./Install.ps1`
1. Run upgrade CLI command `spice upgrade`

```bash
PS C:\spice\test-app> spice upgrade
Checking for latest Spice CLI release...
Upgrading the Spice.ai CLI ...
Error upgrading the spice binary: rename C:\Users\sg\.spice\bin\66216e44\spice.exe C:\Users\sg\.spice\bin\spice.exe: Access is denied.
```

**Expected behavior**
Spice CLI should NOT error and instead print upgrade instructions or successfully complete upgrade.

**Additional context**
You can't replace running binary on Windows

**Comment by Calvindd2f** [comment]
The folder path you are trying to call the upgrade from is `C:\spice\test-app` . The location of the binary is in the user folder `C:\Users\sg\.spice\bin\66216e44\spice.exe` . The downloads go to` C:\Users\sg\AppData\Local\Temp\` then moved to `C:\Users\sg\.spice\bin\spice.exe`

If your powershell session is as Admin, can you try as user. If it as user, can you try as admin. 

It is clearly a problem with writing to the user directory.
