### ISSUE TITLE
Enhancement: support more `tokio-postgres` types

### ISSUE THREAD

**Issue by ahirner** [spiceai/spiceai#1148]
## Goal-State/What/Result

Support the next most important data types.

## Why/Purpose

More supported data types mean more supported datasets.

## Spec

Newly supported types should fit `arrow_sql_gen/src/postgres.rs`.

## How/MAP

A list of `tokio-postgres` to `arrow` types, testing strategy and remarks.

### Implementation (issues)

- [ ] `TIMESTAMPTZ` to `Timestamp(TimeUnit::Millisecond, None)`, testing TBD, not sure if tokio-postgres chrono handles TZ automagically, [draft](https://github.com/ahirner/spiceai/commit/529e05ffbd3c9bc800ae79d719f41d02c90e5a2a)
- [ ] `UUID` to `FixedSizeBinary(16)`, testing TBD, [draft](https://github.com/ahirner/spiceai/commit/257e20712894a765dfdd9693078a11b7e371fe0c)

### QA

The issue would remain open for some feedback on test strategy and more desired types.

**Comment by y-f-u** [comment]
@ahirner , thanks for your drafts, I am looking at this one now. Will do some tests, I've also cherry-pick your changes into #1276
