### ISSUE TITLE
Better Error Message in Spice

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#1161]
## Goal State
Give Spice OSS users less verbose, clearer error messages that directly point to source error.

## Why
Verbose errors can confuse users since they include intermediate error messages before stating the root cause. We therefore redesign to display succinct, direct error messages directly pointing to the root source of the error.
Spice uses `Snafu enum` style errors with the `Display` trait. The current implementation of Error involves nested layers of sources between the error call in runtime and the root cause of the error. It leads to verbose errors that present all Display text in the source chain. 

## Proposed Solution
Refactor Error messages in Spice to only keep the [runtime error message](https://github.com/spiceai/spiceai/blob/trunk/crates/runtime/src/lib.rs) and the root cause error message. Runtime error is where the chain of error starts, root source of error is where the chain of error terminates, oftentimes pointing to the errors of external crates or errors without a source in Spice.

The refactored error will follow the following structure:
`{Runtime Error Message}{Root Source Error Message}`

## Example
This is a verbose error currently in Spice:
`Failed to initialize data connector for dataset eth_recent_blocks: Unable to attach data connector spiceai: Unable to create dataset acceleration: Acceleration creation failed: Unable to create table: External error: Unable to create Postgres connection pool: ConnectionPoolRunError: Timed out in bb8`
After refactor, the error will be:
`Failed to initialize data connector for dataset eth_recent_blocks: Unable to attach data connector spiceai: External error: Timed out in bb8.`
Where `Failed to initialize data connector for dataset eth_recent_blocks: Unable to attach data connector spiceai:` is {Runtime Error Message} and `External error: Timed out in bb8` is {Source Error Message}

## How
To achieve this goal, we only keep the #[snafu(display(“Verbose Text: {source}"))] at runtime and root source of errors. For all intermediate layers, we either use either  #[snafu(transparent)], where error context can be uniquely distinguished by their source error type, or #[snafu(display("{source}"))] where the same types of error source appear in different context

### Summary
* Shorter source chain for #[snafu(display)]
* Separate Rust file for enum Error definition when many variants of error are presented
* Use #[snafu(transparent)] to reduce unwanted nesting in intermediate levels

[Arrow Rust - Object store](https://github.com/apache/arrow-rs/tree/master/object_store)
* Widely uses snafu display
* At most 1 level of nesting of error sources. Most sources directly point to external error

[Octocrab](https://github.com/XAMPPRocky/octocrab)
* Widely uses snafu display
* No nesting of error sources. Only 1 definition of error Enum sources directly points to root source.
* Separate file for error definition at the top level

[Awslabs - Tough](https://github.com/awslabs/tough)
* Widely uses snafu display
* At most 1 level of nesting of error sources. 
* Separate file for error definition at each level

[Guidance From Snafu Documentation](https://docs.rs/snafu/latest/snafu/derive.Snafu.html#delegating-to-the-underlying-error)
* #[snafu(transparent)] can reduce unwanted nesting when error types themselves explains the failure
* Counter Example: The following cannot be converted into transparent because the error doesn’t distinguish itself, i.e. both have source of type: Box<dyn std::error::Error + Send + Sync>
```Rust
    #[snafu(display("Unable to resolve table provider: {source}"))]
    UnableToResolveTableProvider {
        source: Box<dyn std::error::Error + Send + Sync>,
    },
    #[snafu(display("Unable to get object store configuration: {source}"))]
    InvalidObjectStore {
        source: Box<dyn std::error::Error + Send + Sync>,
    },
```

**Comment by digadeesh** [comment]
This is good to keep for context, but I will close this in favor of specific error message improvements per connector.
