### ISSUE TITLE
Raise errors in InsertBuilder up to top

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#1221]
**Describe the bug**
As described in [this comment](https://github.com/spiceai/spiceai/pull/1217#discussion_r1582513965), if an error in the `InsertBuilder` occurs, it is masked. These errors should be bubbled up the whole way (not logged at `build_postgres`, etc and ignored).

**Comment by Jeadie** [comment]
https://github.com/spiceai/spiceai/pull/1242

**Comment by digadeesh** [comment]
Looks like this can be closed.  @Jeadie please reopen if thats not the case.
