### ISSUE TITLE
Enhancement: Snowflake Data Connector Alpha

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1225]
## Goal-State/What/Result

Users can perform federated queries against their snowflake warehouse or accelerate their warehouse data using Spice accelerators. 

Milestones:

- M1 Alpha Support
  - basic Snowflake authentication (username/password)
  - Support for `warehouse` and `role` parameters
  - non-AWS deployments and non-default regions support

Note: full refresh mode for the data connector is sufficient. [Snowflake streams functionality](https://docs.snowflake.com/en/user-guide/streams-intro) for change data capture is out of scope for initial connector implementation.

## Why/Purpose

Snowflake is a leading cloud data warehouse and data platform.  Users that have data in snowflake want to be able to query against this data in Spice.

Using the Spice with the Snowflake data connector allows users to reduce cost by running queries against accelerated local data, preventing the warehouse from waking up, and reducing credit consumption.

## By When

v0.13-alpha

**Issue/Spec written and reviewed:** 04/30

**M1:** 05/10
...
**Done-Done:** 05/10

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
  - [x] ~E2E test for data connector~ (n/a - requires paid Snowflake account) 
  - [x] All Snowflake types tested
  - [x] Acceleration backends with Snoflake data connector
  - [x] Scale/performance using tpch queries and `snowflake_sample_data.tpch_sf10` data
  - [x] User friendly errors
     - auth issue (invalid or missing credentials)
     - invalid warehouse or account id
     - invalid schema/table
     - no connection,
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release notes added

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

#### M1 Alpha Support

[snowflake-api](https://crates.io/crates/snowflake-api) is selected for implementation to provide best developer experience via leveraging Snowflake Arrow Flight endpoint for best performance and get rid of manual steps to configure ODBC/JDBC drivers locally. Comparison of all options available is [here](https://github.com/spiceai/spiceai/issues/1246).

- [x] Snowflake basic (username/password) auth support is added to Spice CLI:
```
spice login snowflake -a account -u username -p password
```
- [x] Snowflake Data Connector can be defined in spicepod:
```
- from: snowflake:database.schema.table
  name: my_table
  params: 
    snowflake_warehouse: warehouse_name
```

- [x] Snowflake data connector can query data from Snowflake instance
 - username/password auth
 - supports SQL queries for the following data types: Numeric, String types,  Boolean, Date, Timestampt
Full list of data types: https://docs.snowflake.com/en/sql-reference/intro-summary-data-types

- [x] Support on non us-west-2 or AWS deployments is tested and documented
- [x] `rolename` parameter is supported (role name to use for queries)

#### M1 Alpha Support
- [x] #1246
- [x] #1259
- [x] #1273
- [x] #1274
- [x] Test Snowflake types support,  scale and acceleration test (test `snowflake_sample_data.tpch_sf10` queries/acceleration)
- [x] Documentation for Snowflake (based on M1 functionality)
- [x] #1287
- [x] #1289

### Implementation (issues)
- https://github.com/spiceai/spiceai/pull/1278
- https://github.com/spiceai/spiceai/pull/1272
- https://github.com/spiceai/quickstarts/pull/105
- https://github.com/spiceai/docs/pull/229
- https://github.com/spiceai/spiceai/pull/1296
- https://github.com/mycelial/snowflake-rs/pull/43
- https://github.com/mycelial/snowflake-rs/pull/42

**Comment by sgrebnov** [comment]
Created separate enhancement to track additional auth methods support for Snowflake: https://github.com/spiceai/spiceai/issues/1331
