### ISSUE TITLE
Enhancement: minimize manual spicepod.yml manipulation in E2E tests

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1226]
## Goal-State/What/Result

Per [discussion](https://github.com/spiceai/spiceai/pull/1218#discussion_r1582528027): there are many places in E2E tests where we construct spicepods manually via string manipulation. If a breaking change is made to the spicepod definition, its hard to find all of these places that would need to be updated. Ideally we could use the CLI or some other tool that manipulates spicepods using our existing spicepod parser.

Milestones:

- M1 <>
- M2 <>
- ...

## Why/Purpose

Clear and concise answer to why this should be done now.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** <Target Date>

**M1:** <Target Date>
**M2:** <Target Date>
...
**Done-Done:** <Target Date>

## Done-Done

- [ ] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [ ] The Algorithm
- [ ] PM/Design Review
- [ ] UX Review
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

## Spec

Basic specification of the enhancement.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- 
-

**Comment by phillipleblanc** [comment]
Not a priority
