### ISSUE TITLE
Enhancement: User Friendly Error messages, PostgreSQL data connector

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1229]
## Goal-State/What/Result

PostgreSQL data connector misconfigurations are user friendly and actionable when the database is either misconfigured or the datbase can't be reached.

Milestones:

- M1: validate postgres connection before returning new pool (should directly connect to postgres, without pool)
- M2: wrap and handle postgres errors, to return user friendly messages

## Why/Purpose

Encountering errors with huge stack traces and limited details on the action is a frustrating experience for customers.

## First Principles:

[Developer experience first](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md#developer-experience-first)

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** Apr 30 (EOD PST)

**M1:** May 1
**M2:** May 2
**Done-Done:** May 3 (optimistically)

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [ ] Documentation
- [x] Samples/Quickstarts/Tutorials

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

### Errors:

**Misconfigured dataset name in "from":**
Current:
> 2024-04-29T21:39:51.443329Z  WARN runtime: Failed to initialize data connector for dataset my_dataset: Unable to attach data connector postgres: Unable to resolve table provider: Unable to get schema: Unable to get schema: db error: ERROR: relation "eth_beacon_recent_slotss" does not exist

Desired:
> 2024-04-29T21:39:51.443329Z  WARN runtime: Failed to initialize data connector for dataset <name>.  Table <table_name_in_from> not found.   Ensure the table name is correctly spelled in the spicepod.

**Misconfigured host or port name**
Current:
> 2024-04-29T21:43:42.024911Z  WARN runtime: Failed to get data connector from source for dataset my_dataset: Unable to initialize data connector postgres: Unable to create Postgres connection pool: ConnectionPoolRunError: Timed out in bb8

Desired:
> Cannot connect to PostgreSQL data connector <name> on <pg_host>:pg_port.  Ensure that the host and port are correclty configured in the spicepod, and that the host is reachable.

**Misconfigured username/password**
Current:
> 2024-04-29T21:47:00.498043Z  WARN runtime: Failed to get data connector from source for dataset my_dataset: Unable to initialize data connector postgres: Unable to create Postgres connection pool: ConnectionPoolRunError: Timed out in bb8

Desired:
> Cannot connect to PostgreSQL data connector <name> on <pg_host>:<pg_port>.  Authentication failed.  Ensure that the username and password are correctly configured in the spicepod.

**pg_sslmode set to enable**
Current:
> 2024-04-29T21:48:26.238748Z  WARN runtime: Failed to get data connector from source for dataset my_dataset: Unable to initialize data connector postgres: Unable to create Postgres connection pool: Invalid parameter: pg_sslmode

Desired:
> Failed to connect to PostgreSQL data connector <name> on <hostname>:<port>.  SSL connection failed.  Ensure that pg_sslmode is correctly configured in the spicepod.

### Criteria for handling errors from external crate:
* **Errors that are expected to happen**. For example, errors that are caused by misconfiguration by users. Always validate upfront and customize the source error message in Spice.
* **Errors that are not expected to happen**. Show the source error message from the external crate.

### Implementation Guideline
Implement a top-level error handler that turns Snafu errors into user-friendly errors. The error handler will go down the Snafu source chain, and use the context to present a user actionable error.

Example: If we have this error stack:

``` 
Failed to initialize data connector for dataset my_dataset   <-- override: "Failed to initialize data connector for dataset. {source}"
  Unable to attach data connector postgres
    Unable to resolve table provider
      Unable to get schema
        Unable to get schema
          db error: ERROR: relation "eth_beacon_recent_slotss" does not exist    <-- override: "Table <table_name_in_from> not found. Ensure the table name is correctly spelled in the spicepod."
 ```
resulting in:
> Failed to initialize data connector for dataset. Table <table_name_in_from> not found. Ensure the table name is correctly spelled in the spicepod.

Errors visibility should be configurable by tracing errors (user errors on default `ERROR` level, internal snafu errors - on `DEBUG`

### Implementation (issues)

- [x] #1269
- [x] #1270
- [x] #1328

Out of scope:
#1268

**Comment by ewgenius** [comment]
@digadeesh in the scope of postgres this is done
