### ISSUE TITLE
Validate Spark Connect with Ethereum datasets

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1237]
Test with:
- [x] `eth.blocks`
- [x] `eth.transactions`
- [x] `eth.logs`
- [x] `eth.contracts`
- [x] `eth.traces`
- [x] `eth.withdrawals`
- [x] `eth.beacon.validators`
- [x] `eth.beacon.slots`
- [x] `eth.beacon.attestations`
- [x] `eth.beacon.deposits`
- [x] `eth.beacon.voluntary_exits`
- [x] `eth.beacon.attester_slashings`
- [x] `eth.beacon.proposer_slashings`
- [x] `eth.beacon.bls_to_execution_changes`
- [x] `eth.beacon.withdrawals`
- [x] `eth.tokens`
- [x] `eth.token_transfers`
- [x] `eth.token_mints`
- [x] `eth.wallet_balances`
- [x] `eth.uniswap_v2.pool_stats`
- [x] `eth.uniswap_v2.pool_stats_detailed`
- [x] `eth.uniswap_v2.event_mints`
- [x] `eth.uniswap_v2.event_burns`
- [x] `eth.uniswap_v2.event_swaps`
- [x] `eth.uniswap_v2.event_syncs`
- [x] `eth.uniswap_v3.pool_stats`
- [x] `eth.uniswap_v3.event_burns`
- [x] `eth.uniswap_v3.event_mints`
- [x] `eth.uniswap_v3.event_swaps`
- [x] `eth.uniswap_v3.event_set_fee_protocols`
- [x] `eth.uniswap_v3.event_collects`
- [x] `eth.uniswap_v3.event_collect_protocols`
- [x] `eth.uniswap_v3.event_flashes`
- [x] `eth.uniswap_v3.event_increase_observation_cardinality_nexts`
- [x] `eth.uniswap_v3.event_initializes`
- [x] `btc.blocks`
- [x] `btc.transactions`
- [x] `btc.transaction_inputs`
- [x] `btc.transaction_outputs`

**Comment by phillipleblanc** [comment]
Bugs:
- #1258
- #1307
- #1308
