### ISSUE TITLE
Accelerating large datasets to file OOM's Using Clickhouse

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1253]
I accelerated a large (1b rows, probably 40gb of data) to file based duckdb and it OOM'd.  Not data was written to the file.

**Expected behavior**
Since its file based, I'd expect we can handle much larger datasets when accelerating to file (assuming there is plenty of disk space).

**Screenshots**
![image](https://github.com/spiceai/spiceai/assets/5965815/eea4129b-2adb-4d9e-9b74-5ffa849aa260)

Query for reproducing
```SQL
create table sample_table(id UInt64, name String, age UInt64, email String, created_date DateTime) ENGINE=MergeTree() ORDER BY id;
 
INSERT INTO sample_table (id, name, age, email, created_date) SELECT number AS id, 'name' || toString(number) as name, number % 100 AS age, 'email' || toString(number) || '@example.com' AS email, today() AS created_date FROM numbers(10000000000);
```

**Comment by phillipleblanc** [comment]
@Sevenannn to close and point to enhancement

**Comment by Sevenannn** [comment]
Check https://github.com/spiceai/spiceai/issues/1485 for the implementation
