### ISSUE TITLE
Error message for conflicting config needs improvement

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1256]
**Describe the bug**
Acclerate data with in-memory arrow and set the mode to file.

Observe the following error:
2024-05-01T00:55:54.179088Z  WARN runtime: Failed to initialize data connector for dataset sample_table: Unable to attach data connector clickhouse: Unable to create dataset acceleration: Invalid configuration: File mode not supported for Arrow engine

**Expected behavior**
Remove the nested traces.  Give the user actionable feedback to update their spicepod.

**Comment by Sevenannn** [comment]
The error in logs shows actionable details for user to change config `File mode not supported for Arrow engine`. Close this ticket for now.

TODOs in the future:
* A matrix for data connector / data accelerator error refactorization, to keep track on which connectors/ accelerators have errors left to be improved.
* A written guideline for error wording in Spice.
