### ISSUE TITLE
Improve PostgreSQL connection error

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1260]
PostgreSQL connection error is hard to troubleshot. Below is connection error related to ssl mode. Looking to this message it is hard to tell what is the problem - server is not available (incorrect host and port), invalid user name/password, ssl mode.

>2024-05-01T00:42:13.151876Z WARN runtime: Failed to initialize data connector for dataset eth_recent_blocks: Unable to attach data connector spiceai: Unable to create dataset acceleration: Acceleration creation failed: Unable to create table: External error: Unable to create Postgres connection pool: ConnectionPoolRunError: Timed out in bb8

**Comment by digadeesh** [comment]
Tracked in #1229 .  Closing as duplicate.
