### ISSUE TITLE
Enhancement: Improved telemetry & dashboard

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1283]
## Goal-State/What/Result

Spice is instrumented to provide the following metrics:

- Query execution time (p50,p75,p90,p95,p99)
- Refresh fails (by dataset)
- Offline datasets (connection/auth errors - either during or after startup)
- Failing queries (with errors)
- Accelerated table last updated (by dataset)
- p50,p75,p90,p95,p99 for all duration metrics.

And this is visualized on the Grafana dashboard.

## Why/Purpose

Unblock production usage of Spice

## By When

**Issue/Spec written and reviewed:** May 31, 2024

**Done-Done:** Thu, June 6, 2024

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] ~Tests~
- [x] ~Documentation~
- [x] ~Samples/Quickstarts/Tutorials~
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

Alignment should be to OTEL spec where possible: https://github.com/open-telemetry/opentelemetry-specification

### - [x] `Query duration`
  **name**: `query_duration_seconds`
  **value**: The total duration that the query took (including queuing, execution, streaming results - until the last chunk of data was returned), measured in floating seconds (i.e. `1.15`).
  **percentile**: p50, p75, p90, p95, p99
  **dimensions**:
    `tags`: [accelerated, cache-hit] -> Indicates if this query involved a dataset that was accelerated.
    `datasets`: [blocks, logs] -> Comma separated list of datasets that were involved in the query
    `protocol: http | flight | etc` -> Which API was used to make the request (HTTP or Flight)

Visualization:
 - `SQL Query Engine` panel with chart showing queries duration aggregated by protocol (`http`, `flight`, etc) and for selected `percentile`
 - Percentile format is `p90`, etc
 
![image](https://github.com/spiceai/spiceai/assets/981580/82fca8f6-0cd1-4d00-a4fa-824ef6e769ab)

### - [x] `Failing queries`
  **name**: `query_failures`
  **value**: Count of query failures
  **dimensions**:
    `tags`: [accelerated, cache-hit] -> Indicates if this query involved a dataset that was accelerated.
    `datasets`: [blocks, logs] -> Comma separated list of datasets that were involved in the query
    `protocol: http | flight | etc` -> Which API was used to make the request (HTTP or Flight)
    `err_code`: string:
       - `SyntaxError` - sql is syntactically incorrect
       - `QueryPlanningError` - error while planning of the query (missing table or column)
       - `DataReadError` - error when reading data from an object_store(DataConnector is unable to read the data)
       - `UnexpectedError` - other errors
 
Visualization
- `SQL Query Engine` bar chart (vertical columns) showing number of failed queries per `error_code
![image](https://github.com/spiceai/spiceai/assets/981580/704c89ed-bdbd-4ffc-a3d8-64f24ce37ffb)

### - [x] `Time since last refresh`
  **name**: `datasets_acceleration_last_refresh_time` (TIMESTAMP)
  **value**: A gauge with the timestamp in Unix seconds since the last time a successful refresh of an accelerated dataset occurred.
  **dimensions**:
    `dataset`: str -> The dataset in question
    `refresh_sql`: str -> The refresh SQL used (if any configured)

Visualization
- `Accelerated Datasets` panel: horizontal Bar Guage under
![image](https://github.com/spiceai/spiceai/assets/981580/ed576e78-75a2-48fd-871d-8f8bf7b3d999)

### - [x] `Refresh fails`
  **name**: `datasets_acceleration_refresh_errors`
  **value**: Count of times we tried to load/refresh an accelerated dataset and failed 
  **dimensions**:
    `dataset`: str -> The dataset that failed to load

Visualization
- `Accelerated Datasets` panel: bar chart (vertical columns) with refresh failures aggregated by dataset name

### - [ ] `Time Since Offline`
  **name**: `datasets_unavailable_time` (TIMESTAMP)
  **value**:  Time when a dataset went offline . This is measured by observing requests against the federated dataset or making synthetic connection requests if no requests are happening. It is considered unavailable if no successful request could be made since Spice has started, or no request has been successful for the past 10 minutes.
  **dimensions**:
    `dataset`: str -> The dataset that is unavailable.

Applied only for non-accelerated datasets.

Visualization
- List of offline datasets with offline duration (since dataset creation or last successful query). Name should be `Time Since Offline`
![image](https://github.com/spiceai/spiceai/assets/981580/fc7c0390-e884-4713-9fe9-1d8a29f9ee43)

-[ ] Benchmark tests for query engine performance - concurrent light queries with focus on testing Spice custom logic overhead on top of main query engine. Run tests before and after enhancement to ensure no regression

## How/MAP

- Leveraging the query_history table where we can.
- `datasets_unavailable_time` implementation is the following:
  - During datasets registration, create a hash table of datasets and their types: Federated, Accelerated, etc.
  - Every 1 minute, check if there are Federated datasets without a successful query record in the internal hash table (`dataset-name` -> `last_successful_query_time`) and in the `runtime.query_history` table within the last 10 minutes. Update `last_successful_query_time` if there are more recent queries in `runtime.query_history`.
  - For each dataset without recent queries (>=10 min), perform a synthetic query using the `TableProvider.schema()`
  - Report datasets_unavailable or update the corresponding last_successful_query_time record based on the health check step above.

### Implementation (issues)
- https://github.com/spiceai/spiceai/pull/1575
- https://github.com/spiceai/spiceai/pull/1589
- https://github.com/spiceai/spiceai/pull/1639
- https://github.com/spiceai/spiceai/pull/1598
- https://github.com/spiceai/spiceai/pull/1650
- https://github.com/spiceai/spiceai/pull/1664
- https://github.com/spiceai/spiceai/pull/1661

### QA

Load Spice, start the metrics endpoint, perform several queries and observe that the expected metrics are being emitted. Author an integration test where feasible to test this automatically.

**Comment by phillipleblanc** [comment]
@digadeesh to assign this.

**Comment by sgrebnov** [comment]
-`Query duration`, `Queries failures`, `Time since last refresh`, `Refresh failures` - done (including charts/dashboard)
-`Time Since Offline` is in progress (ETA - Mon 06/10)

**Comment by sgrebnov** [comment]
Enhancement is implemented, the following additional improvement items were created
- https://github.com/spiceai/spiceai/issues/1611
- https://github.com/spiceai/spiceai/issues/1662
