### ISSUE TITLE
Enhancement: Improved federated query pushdown

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1318]
## Goal-State/What/Result

Queries involving a single table in a federated query engine pushes through the entire query to that engine, and no work is done in DataFusion to the results. Logically the query text will just be passed from DataFusion to the Query Engine directly.

More complex queries involving multiple federated tables and other sources will send as much of the computation to be done by each remote query engine as possible. "As much as possible" will be a best effort approach for now and will be improved over time as we get more concrete use-cases, but should cover the majority of the most common ones.

Specifically, that means enabling support for sorting (i.e. TopK), aggregations and joins. As an example, these queries will all be pushed down properly:
- `SELECT * FROM table ORDER BY col LIMIT 10` (i.e. TopK)
- `SELECT max(number) FROM table` (aggregation)
- `SELECT max(number), service FROM table GROUP BY service` (aggregation)
- `SELECT t.id, t.name, r.description FROM table1 t JOIN table2 r ON t.id = r.id` (joins between two tables in the federated source)

## Why/Purpose

This will be needed to enable more efficient queries that perform aggregations, sorts and joins between two tables in the same federated source.

## By When

**Issue/Spec written and reviewed:** May 8, 2024

**M1:** May 10, 2024
**M2:** May 15, 2024
**M3:** May, 17, 2024
...
**Done-Done:** <Target Date>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

Implement the trait [`SQLExecutor`](https://github.com/datafusion-contrib/datafusion-federation/blob/main/sources/sql/src/executor.rs#L12C1-L12C35) for [`SqlTable`](https://github.com/spiceai/spiceai/blob/trunk/crates/sql_provider_datafusion/src/lib.rs#L60). This will cover all of the DataConnectors that use that for the TableProvider implementation: MySQL, PostgreSQL, Snowflake, Sqlite, ODBC, DuckDB and Clickhouse.

Modify the `FederatedTableProviderAdaptor` (or create our own) to support insertion.

Implement the `SQLExecutor` trait for `FlightTable` & `FlightSQLTable` (for Dremio, FlightSQL & Spice.ai data connectors).

Implement the `FederationProvider` for Spark Connect. Spark Connect is a little special because it doesn't accept SQL directly, so it might require more work to translate from all DataFusion expressions to Spark Connect expressions.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- [x] #1345
- [x] #1352
- [x] #1346
- [x] #1398
- [x] #1347
- [x] #1348 
- [x] #1396
- [x] #1397
- [x] #1379
- [x] #1448

### QA

Add tests that the proper SQL is being generated and sent to remote SQL query engines.

There should be no difference in performance from running via Spice vs running in the source directly when we get 100% pushdown. Add tests to cover this.

Inspect the query plans for cross source queries that we expect to be common and validate that the SQL being sent to the source covers all of the execution that could logically be done by that source.

**Comment by phillipleblanc** [comment]
UNION ALL push-down is not implemented in DataFusion: https://github.com/apache/datafusion/blob/main/datafusion/sql/src/unparser/plan.rs#L351

**Comment by phillipleblanc** [comment]
Phillip to fix all known bugs, do performance testing and split out the Spark push-down into a separate ticket.

**Comment by y-f-u** [comment]
#1496 is also caused by the federated query push down.

DF always use int64 for count aggregate query, but with federated pushdown the count query is sent to remote and the data returned could be in Int32. E.g. select count(1) from snowflake_table.

With select count(1) from snowflake_table limit 1 returns int64 and that is why it worked.

**Comment by phillipleblanc** [comment]
Closing as done
