### ISSUE TITLE
Enhancement: HuggingFace model format detection and model download

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1332]
## Goal-State/What/Result

A clear and concise description of what the enhancement is and the target goal-state.

Milestones:

- M1 <>
- M2 <>
- ...

## Why/Purpose

Clear and concise answer to why this should be done now.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** <Target Date>

**M1:** <Target Date>
**M2:** <Target Date>
...
**Done-Done:** <Target Date>

## Done-Done

- [ ] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [ ] The Algorithm
- [ ] PM/Design Review
- [ ] UX Review
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials
- [ ] Release Notes

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

## Spec

Basic specification of the enhancement.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- 
-

**Comment by phillipleblanc** [comment]
@Jeadie to close this if not needed

**Comment by Jeadie** [comment]
We currently have support for users to specify which model within a HF repo to use, and support for multiple model formats. This is no longer a priority
