### ISSUE TITLE
Enhancement: LRU cache for query results

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1358]
## Goal-State/What/Result

In-memory LRU caching of query results

Example:

```yaml

runtime:
  results_cache:
    enabled: true
    cache_max_size: 128MiB
    eviction_policy: lru 
    item_ttl: 1s

datasets:
   ...
```

## Why/Purpose

To provide accelerated performance for federated and fallback queries (in conjunction with [behavior on zero results](https://docs.spiceai.org/data-accelerators#behavior-on-zero-results)) and to prevent many redundant queries within a small time period.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** 05/20
...
**Done-Done:** 05/23

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

- [x] Cache configuration
```
runtime:
  results_cache:
    enabled: true
    eviction_policy: lru 
    cache_max_size: 128mb
    item_ttl: 1s
```
- `enabled` - optional, true by default (if there is a non-empty results_cache section defined)
- `cache_max_size` - optional, maximum cache size. Default is 128mb
- `item_ttl` - optional, cache entry expiration time, 1 second by default. Duration format follows existing conventions in Spice
- `eviction_policy` - optional, specifies the eviction policy to be used when the cached data reaches the `cache_max_size`. The default and currently the only supported policy is 'lru'.
- [x] New telemetry events are added: 
  - results_cache_request_count
  - results_cache_hit_count
  - results_cache_size
  - results_cache_item_count
  - results_cache_max_size
- [x] New cache header is added to Spice http query response: `X-Cache: HIT/MISS` (no etag, age for simplicity). Exists only when cache is enabled.
- [x] Caching is enabled by default
- [x] #1522

Out of scope for LRU cache alpha
- Header/option to bypass Cache
- Manual cache eviction (API/CLI)
- Cache hit/miss indication when using Spice REPL

## How/MAP
- [x] #1422
- [x] #1423
- [x] #1424
- [x] #1425
- [x] #1471
- [x] #1457
- [x] #1499
- [x] #1488
- [x] #1491

### Implementation (issues)
- https://github.com/spiceai/spiceai/pull/1410
- https://github.com/spiceai/spiceai/pull/1450
- https://github.com/spiceai/docs/pull/257
- https://github.com/spiceai/quickstarts/pull/120
- https://github.com/spiceai/spiceai/pull/1472
- https://github.com/spiceai/spiceai/pull/1498
- https://github.com/spiceai/spiceai/pull/1473
- https://github.com/spiceai/spiceai/pull/1487
- https://github.com/spiceai/spiceai/pull/1515
- https://github.com/spiceai/spiceai/pull/1514
- https://github.com/spiceai/spiceai/pull/1513
- https://github.com/spiceai/spiceai/pull/1528

**Comment by digadeesh** [comment]
what does the unit for size mean?  number of rows?

**Comment by phillipleblanc** [comment]
Close after getting UX/PM signoff

@sgrebnov will drive this

**Comment by sgrebnov** [comment]
Enhancement is implemented. 

We would like to also implement `Cache hit/miss indication when using Spice REPL` but it should be tracked separately (@sgrebnov will own/drive this). 

UX for REPL indication:
```
Time: 0.011118041 seconds. 1 rows. <- miss or no cache
Time: 0.011118041 seconds. 1 rows (cached). <- from cache
```
