### ISSUE TITLE
Refresh status in spice runtime output should show when its done, and show the number of rows refreshed

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1376]
**Describe the bug**
Spice runtime will show that its refreshing data into an accelerator, but it'll never indicate when its finished.  Example:

![image](https://github.com/spiceai/spiceai/assets/5965815/a1988902-a035-46ca-9ea1-6074ef3a775c)

**To Reproduce**
Load the sample S3 data using the spice runtime.  Follow the README to complete the steps.

Observe that it shows its refreshing data, but never states when its completed (see screenshot).

**Expected behavior**
A log message indicating that its done loading, and displaying the number of rows that were loaded during the refresh.

**Comment by lukekim** [comment]
Ideally also show the size of the data. Something like:

`runtime:: accelerated_table::refresh: Loaded 87 rows (36 MiB) for dataset taxi_trips in 56 seconds.`

Note, `[refresh]` is redundant and should be removed.
