### ISSUE TITLE
Performance testing benchmarks

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1379]
Part of #1318 

Collect some performance benchmarks for the before/after of federation.

**Comment by lukekim** [comment]
As part of this issue, let's improve the [TPC-H Benchmark](https://github.com/spiceai/spiceai/actions/workflows/tpch_benchmark.yml) workflow to add a replicated dataset to the Spice runtime that replicates the results back to the Spice.ai Cloud Platform so we can chart and track the trend.
