### ISSUE TITLE
Store query history in `spice.runtime.query_history` table

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#1389]
Create a new `spice.runtime.query_history` prefixed table that holds the history of jobs ran by the runtime. Columns

- query_id
- schema
- sql
- text (nullable, present for NSQL queries)
- start_time
- end_time
- execution_time
- rows_produced
- results_cache_hit

See #1361 for comparison.

**Comment by Jeadie** [comment]
Need to think more about schema

**Comment by Jeadie** [comment]
Or in `INFORMATION_SCHEMA`

**Comment by phillipleblanc** [comment]
@Jeadie to close this as its done.
