### ISSUE TITLE
Enhancement: Improve dataset registration output

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1440]
## Goal-State/What/Result

Dataset registration output includes caching and acceleration information about the dataset.

## Why/Purpose

To help the user confirm the configuration of each dataset at runtime to avoid misconfiguration issues.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** 06/13
**Done-Done:** 06/14

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## Spec

1. Should include `from` spec information.
1. Should include information whether results cache is enabled
1. For accelerated datasets should include acceleration with engine informational text: `with acceleration(<engine>, <optional refresh interval>, <optional retention check interval>, <optional information about fallback on source>)`
 - If refresh is on: include refresh check interval information as `30s refresh`
 - If retention is on: include retention check interval information as `1hr retention`
 - If non-default on_empty_result fallback add "fallback on source on empty result"
 - for file mode use `acceleration (sqlite:file)` format

Examples:

```bash
Dataset taxi_trips registered (s3://spiceai-demo-datasets/taxi_trips/2024/), results cache enabled.
Dataset taxi_trips registered (s3://spiceai-demo-datasets/taxi_trips/2024/), acceleration (duckdb), results cache enabled.
Dataset taxi_trips registered (s3://spiceai-demo-datasets/taxi_trips/2024/), acceleration (sqlite:file, 30s refresh).
Dataset nation registered (spiceai:tpch.nation), acceleration (sqlite, 30s refresh, 1hr retention).
Dataset nation registered (spiceai:tpch.nation), acceleration (sqlite, fallback on source on empty result).
```

## How/MAP
 - [x] Update registration output
 - [x] Update [README.md](https://github.com/spiceai/spiceai/blob/trunk/README.md) with updated registration output

### Implementation (issues)
- https://github.com/spiceai/spiceai/pull/1692
- https://github.com/spiceai/spiceai/pull/1694

**Comment by phillipleblanc** [comment]
@sgrebnov set a target date, then spec out the issue. Add examples of what we expect the logs to look like after this is done.

**Comment by sgrebnov** [comment]
Implemented
