### ISSUE TITLE
Missing table exposes default catalog schema in http/flight response

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#1470]
**Describe the bug**

When querying from non-existent table, error from http or flight request exposes internal spice structure

![CleanShot 2024-05-22 at 08 44 56@2x](https://github.com/spiceai/spiceai/assets/827338/58f9ba8f-89d4-45af-9b4b-72f70917d311)

![CleanShot 2024-05-22 at 08 49 17@2x](https://github.com/spiceai/spiceai/assets/827338/90e89972-3b44-4c62-9677-487036d71da5)

**Expected behavior**

Error message should not include internal details

**Comment by phillipleblanc** [comment]
This is expected behavior
