### ISSUE TITLE
Enhancement: Improve spice runtime memory usage when accelerating with file-based accelerator in full refresh mode

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#1485]
## Goal-State/What/Result

Large dataset won't get stuck in spice runtime memory and cause excessive memory usage / OOM of spice runtime when accelerating in full refresh mode with file-based accelerator.

## Why/Purpose

Full refresh mode with a file-based accelerator causes excessive memory usage / OOM when accelerating large datasets.

## By When

**Issue/Spec written and reviewed:** Wed May 22
**Done-Done:** TBD

## Done-Done

- [ ] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [ ] The Algorithm
- [ ] PM/Design Review
- [ ] UX Review
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials
- [ ] Release Notes

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

## Spec

- stream from data connector all the way through to the batch insert
- data connectors support either stream or batch fetch that does not require loading all data in a table at once.
- data insertion into accelerator supports batch insertion within a transaction; memory released after each batch insertion

### Current Problem
Full refresh waits for all data to be collected from data connector before writing to the data accelerator. Data collected from data connector accumulate in Spice runtime and uses huge memory.

## How/MAP

- [x] #1797
- [x] #1570 
- [x] #1778
- [x] #1779
- [x] #1780
- [x] #1781
- [x] #1782
- [x] #1783

### QA

- [ ] monitor resource while loading large data from various connectors into various data accelerator.

**Comment by phillipleblanc** [comment]
Assigning to @ewgenius as lowest priority.

**Comment by sgrebnov** [comment]
Update on streaming write for acceleration engines:
1. Common logic for streaming write (refresh) is implemented, remaining step - update specific TableProviders (DuckDB, SQLite) to rely on streaming. PostgreSQL impl is already based on streaming, no AIs
1. DuckDB - implemented,  waiting for the following PR to be reviewed/approved: [Streaming write for DuckDB TableProvider](https://github.com/datafusion-contrib/datafusion-table-providers/pull/6).
1. SQLite: we currently rely on single-threaded approach for SQLite (single connection and thread per table) which will block all queries until stream writing is completed. This is not how we want this to work so we should revisit overall approach for sqlite (different crate or dedicated connection instance just for writing) before implementing streaming support

**Comment by phillipleblanc** [comment]
Closing as done. There are two remaining issues that are being tracked separately:
https://github.com/spiceai/spiceai/issues/1780
https://github.com/spiceai/spiceai/issues/1783
