### ISSUE TITLE
Bug: select count(1) from snowflake federated table returns error

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#1496]
**Describe the bug**
For snowflake data connector, select count(1) from a table will return an error, but with `limit 1` succeeds.

**To Reproduce**
```
sql> select count(1) from lineitem;
Unexpected Flight Error Decode error: Error decoding ipc RecordBatch: Invalid argument error: Need at least 8 bytes in buffers[0] in array of type Int64, but got 4
sql> select count(1) from lineitem limit 1;
+-----------------+
| COUNT(Int64(1)) |
+-----------------+
| 6001215         |
+-----------------+

Time: 0.469795583 seconds. 1 rows.
```

**Expected behavior**

Both succeeds.

**Comment by phillipleblanc** [comment]
The issue here is that Snowflake is returning an Int32 for the count value, whereas the schema DataFusion expects is an Int64.
