### ISSUE TITLE
Code review all critical query code paths to ensure highest possible query performance

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1534]
## Goal-State/What/Result

All critical query code paths are code reviewed for performance concerns and any issues resolved.

## Why/Purpose

Query performance is critical to the core value proposition of Spice.

## By When

For beta.

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

Basic specification of the enhancement.

## How/MAP

- [x] Review the call tree structure.
- [x] Review uses of arg passing (ref/val), stack vs heap, etc. 
- [x] Review uses of `.clone()` in the critical path.
- [x] Review all loops and recursion.

### Implementation (issues)

- 
-

**Comment by phillipleblanc** [comment]
Marking this as done with both #2136 and #2138 completed.
