### ISSUE TITLE
Implement Decimal128 conversion in DataFusion Unparser

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1578]
**Describe the bug**
The unparser code in DataFusion (responsible for turning LogicalPlans back into SQL statements) does not handle Decimal128 values, which causes several of the TPC-H queries to fail with the following error:
`Error: "query tpch_q1 to results: External error: This feature is not implemented: Unsupported DataType: conversion: Decimal128(20, 0)"`

The relevant code that needs to be implemented:
https://github.com/apache/datafusion/blob/1db3263497532fda5167386781755463f53c00a4/datafusion/sql/src/unparser/expr.rs#L913

This affects the following benchmark queries:
- `tpch_q1`
- `tpch_q3`
- `tpch_q5`
- `tpch_q10`
- `tpch_q11`
- `tpch_q16`
- `tpch_q17`
- `tpch_q18`
- `tpch_q22`

**Comment by y-f-u** [comment]
tpch 11,17,18,19 are fixed, the rest will move to #1765 or the error is updated accordingly in the benchmark mod.rs.
