### ISSUE TITLE
Unable to query Flight: Unknown identifier 'DATETIME'

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1582]
**Describe the bug**
An error is returned from running `tpch_q12` against the Spice Cloud system with the following message:

`Error: "query tpch_q12 to results: External error: Execution error: Unable to query Flight: Unable to query: status: InvalidArgument, message: \"Unknown identifier 'DATETIME'`

**To Reproduce**
Uncomment `tpch_q12` from the benchmark tests and run.

**Expected behavior**
Dialects are used to substitute keywords that don't exist in one system.

**Comment by phillipleblanc** [comment]
@edmondop said he wanted to take a shot at this and #1583

**Comment by digadeesh** [comment]
Fixed in #1946
