### ISSUE TITLE
`time_format` should support `timestamp` and `timestampz`

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#1754]
Internally, DataFusion type`:

`timestamp` = `Timestamp(Millisecond, [tz])`
`timestampz` = `Timestamp(Millisecond, None)`

See also https://www.postgresql.org/docs/current/datatype-datetime.html

**Comment by phillipleblanc** [comment]
This is already supported. The `time_format` is only needed if the Arrow type is ambiguous (i.e. a raw integer type or string type). For timestamp/time types, we already do the right thing.

https://github.com/spiceai/spiceai/blob/trunk/crates/runtime/src/datafusion/filter_converter.rs#L72-L76
