### ISSUE TITLE
DuckDB Data Connector supports streaming or batch fetch

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#1780]

**Comment by Jeadie** [comment]
The C API for streaming queries: https://github.com/duckdb/duckdb/pull/6318
Not supported within Duckdb-rs. Issue: https://github.com/duckdb/duckdb-rs/issues/171

**Comment by Jeadie** [comment]
Difficulty with using the new C-API FFIs `duckdb_pending_prepared_streaming`, `duckdb_create_streaming_result`, & `duckdb_stream_fetch_chunk` is that these do not produce arrow-compatible results (unlike the current`duckdb_execute_prepared_arrow` and `duckdb_query_arrow_schema`)

**Comment by sgrebnov** [comment]
To improve performance + memory usage we can replace `collect` with streaming approach as DuckDB implements stepped approach to convert internal query result to arrow. 


```rust
        let mut stmt = self.conn.prepare(sql).context(DuckDBSnafu)?;

        let result: duckdb::Arrow<'_> = stmt.query_arrow(params).context(DuckDBSnafu)?;
        let schema = result.get_schema();

        let recs: Vec<RecordBatch> = result.collect(); // currently
```

DuckDB uses `duckdb_query_arrow_array` to collect results internally and return results as record batch chunks. `result` is actually an iterator where next batch is created once requested and we should rely on this.

```
    #[inline]
    pub fn step(&self) -> Option<StructArray> {
        self.result?;
        unsafe {
            let mut arrays = FFI_ArrowArray::empty();
            if ffi::duckdb_query_arrow_array(
                self.result_unwrap(),
                &mut std::ptr::addr_of_mut!(arrays) as *mut _ as *mut ffi::duckdb_arrow_array,
            )
            .ne(&ffi::DuckDBSuccess)
            {
                return None;
            }

            if arrays.is_empty() {
                return None;
            }

            let mut schema = FFI_ArrowSchema::empty();
            if ffi::duckdb_query_arrow_schema(
                self.result_unwrap(),
                &mut std::ptr::addr_of_mut!(schema) as *mut _ as *mut ffi::duckdb_arrow_schema,
            ) != ffi::DuckDBSuccess
            {
                return None;
            }

            let array_data = from_ffi(arrays, &schema).expect("ok");
            let struct_array = StructArray::from(array_data);
            Some(struct_array)
        }
    }
```

If I process results by batches I see memory usage drop by a factor of ~2 (12gb max vs  6gb max) as we avoid storing all batches in memory plus this should lead to better performance as we can start processing batches once results are ready, not last batch is prepared.

```rust
for batch in result {
        num_batches += 1;
        println!("Batch: {} num records {} ", num_batches, batch.num_rows());
}
```

```
Batch: 13632 num records 2048 
Batch: 13633 num records 2048 
Batch: 13634 num records 2048 
Batch: 13635 num records 2048 
```

**Comment by sgrebnov** [comment]
Note: main complexity here will be implementation based on thready safety (not sync/send) limitations and taking into account current version of query_arrow is also not async.

**Comment by sgrebnov** [comment]
No good luck with full streaming support - requires proper env setup and testing, found few places where this could be potentially added,  but have not ha enough time to complete testing end to end

**Comment by y-f-u** [comment]
Pending on the merge of https://github.com/duckdb/duckdb-rs/pull/373.

Or need to update datafusion-table-provider to use spiceai/duckdb-rs. There is a PR in datafusion-table-provider that has the work of using duckdb-rs change for this: https://github.com/datafusion-contrib/datafusion-table-providers/pull/41
