### ISSUE TITLE
DuckDB writes data utilizing stream rather than Vec[RecordBatch]

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#1782]

**Comment by sgrebnov** [comment]
Awaiting the following PR to be reviewed/approved: [Streaming write for DuckDB TableProvider](https://github.com/datafusion-contrib/datafusion-table-providers/pull/6)

**Comment by sgrebnov** [comment]
Completed by https://github.com/spiceai/spiceai/pull/1884
