### ISSUE TITLE
GraphQL `json_path` is not really a JSON path

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1858]
**Describe the bug**
Attempting to use more advanced JSON Path syntax does not work, because its not actually JSON Path. This is not well documented and misleading.

It isn't actually JSON Path, but a JSON Pointer as defined by [RFC 6901 - JavaScript Object Notation (JSON) Pointer (ietf.org)](https://datatracker.ietf.org/doc/html/rfc6901) - which is very different and much more limited.

We should rename `json_path` to `json_pointer` and provide better documentation on how what syntax is allowed and common examples on how to use it.

**Comment by digadeesh** [comment]
If we switch to the JSON  pointer we'll want to adopt the syntax / format of a JSON pointer in the spicepod, which is slightly different
