### ISSUE TITLE
Bug: PostgreSQL, AWS Aurora Postgres, Supabase, AWS RDS Postgres TPCH Query 11, 14, 17, 20 Type Double not exist error 

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#1928]
**Describe the bug**
When running TPCH query 11 without accleration when connecting to PostgreSQL / AWS Aurora / Supabase using Postgres Data Connector, the following error is shown:
```
Status { code: Internal, message: "External error: Execution error: Unable to query arrow: db error: ERROR: type \"double\" does not exist", source: None }
```

**To Reproduce**
Run TPCH query 11 in Spice REPL, using Postgres data connector connecting to PostgreSQL / AWS Aurora / Supabase, without acceleration
```TPCH
select
    ps_partkey,
    sum(ps_supplycost * ps_availqty) as value
from
    partsupp,
    supplier,
    nation
where
    ps_suppkey = s_suppkey
  and s_nationkey = n_nationkey
  and n_name = 'GERMANY'
group by
    ps_partkey having
    sum(ps_supplycost * ps_availqty) > (
    select
    sum(ps_supplycost * ps_availqty) * 0.0001
    from
    partsupp,
    supplier,
    nation
    where
    ps_suppkey = s_suppkey
                  and s_nationkey = n_nationkey
                  and n_name = 'GERMANY'
    )
order by
    value desc;
```

**Expected behavior**

**Spicepod**
Add the relevant `spicepod.yml` section.

**Output of the `describe table`**
Add any relevant `describe table` output here.

**Output of `explain query`**
Add any relevant `explain query` output here.

E.g. `explain select 1`
```
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

**spice, spiced, OS info**
- spice version: CLI version:     v0.15.2-alpha-rc.12c3be57
Runtime version: v0.15.2-alpha-rc.10ffdb8c
- spiced version: v0.15.2-alpha-rc.10ffdb8c
- OS info: Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64

**Have you tried this on the latest `trunk` branch?**

**If possible, run `spiced` with DEBUG log level**

By setting the environment variable `SPICED_LOG="spiced=DEBUG,runtime=DEBUG,data_components=DEBUG,cache=DEBUG"`

**Screenshots**

**Additional context**

**Comment by peasee** [comment]
I get the same errors with Postgres over ODBC as well
