### ISSUE TITLE
Explicit development and production runtime modes

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#194]
In production, no file-watcher for changes in pod manifest or configuration. Expected to deploy and use specific pre-provided manifests in production.

Development mode will be set on `spiced` with `-development` defaulting to "production" if not provided. `spice` CLI will always set the `-development` flag when it starts `spiced`.

**Comment by haardvark** [comment]
I don't think this is actually complete yet - the spiced changes are in via #286, but the CLI setting/passing through the dev flag described above is not yet chained in.

**Comment by haardvark** [comment]
NVM - I think I'm following what's going on now.  `spice` will *only* run in dev mode
