### ISSUE TITLE
Bug: MySQL error `Every derived table must have its own alias`

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1952]
**Describe the bug**

When running TPCH query 13 with MySQL, the following rewritten query is generated and is failed to execute with the following error 'Every derived table must have its own alias'

```sql
SELECT
	`c_orders`.`c_count`,
	COUNT(1) AS `custdist`
FROM
	(
	SELECT
		`customer`.`c_custkey` AS `c_custkey`,
		`COUNT(orders.o_orderkey)` AS `c_count`
	FROM
		(
		SELECT
			`customer`.`c_custkey`,
			COUNT(`orders`.`o_orderkey`)
		FROM
			`customer`
		LEFT JOIN `orders` ON
			((`customer`.`c_custkey` = `orders`.`o_custkey`)
				AND `orders`.`o_comment` NOT LIKE CAST('%special%requests%' AS CHAR))
		GROUP BY
			`customer`.`c_custkey`)) AS `c_orders`
GROUP BY
	`c_orders`.`c_count`
ORDER BY
	`custdist` DESC,
	`c_orders`.`c_count` DESC
```

Note: `CAST('%special%requests%' AS TEXT))` was manually replaced with `CAST('%special%requests%' AS CHAR))` due to another but;

**Comment by peasee** [comment]
Postgres over ODBC has a similar error:

```
ERROR: subquery in FROM must have an alias;\nNo query has been executed with that handle
```

**Comment by Sevenannn** [comment]
Postgres data connector over Postgres, Aurora, Supabase has the same error
- https://github.com/spiceai/spiceai/issues/1929

**Comment by sgrebnov** [comment]
This has been fixed (at least for MySQL) by the following PR: https://github.com/spiceai/spiceai/pull/2001

**Comment by peasee** [comment]
MySQL still experiences this error with TPC-DS Q91
