### ISSUE TITLE
Enhancement: Spice AI Data Connector Append Stream Support

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#1960]
REMEMBER, BE **SMART**!

S: Specific
M: Measurable
A: Achievable
R: Relevant
T: Time-Bound

## Goal-State/What/Result

Support the append refresh mode without time_column using the append data stream in Spice AI Data Connector.

## Why/Purpose

The spice ai data connector append refresh mode without time_column is not subscribing to the spiced and fetching new data into accelerator and need to be fixed.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** 2024/7/10
**Done-Done:** TBD

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

* Subscribing to the change data stream using the DoExchange method in the Spice AI data connector. 
* Route dataset with append refresh mode and without time_column to use the acceleration logic of change refresh mode.
* Configure server DoExchange handler to send a ChangeEnvelope format data back to client.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- https://github.com/spiceai/spiceai/pull/1935
- https://github.com/spiceai/spiceai/pull/1958
- https://github.com/spiceai/spiceai/issues/1961

**Comment by digadeesh** [comment]
@Sevenannn and @y-f-u  to sync on the append logic.

**Comment by phillipleblanc** [comment]
Goal: Done-Done by Wednesday.
