### ISSUE TITLE
Enhancement: Use connection pooler to manage flight client

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1968]
if changing the connection pooler lib, make sure it's working for postgres too.

## Goal-State/What/Result

A clear and concise description of what the enhancement is and the target goal-state.

## Why/Purpose

Clear and concise answer to why this should be done now.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [ ] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [ ] The Algorithm
- [ ] PM/Design Review
- [ ] UX Review
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials
- [ ] Release Notes

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

## Spec

Basic specification of the enhancement.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- 
-

**Comment by phillipleblanc** [comment]
We don't need a connection pool for flight, but it can definitely be improved to be more efficient.
