### ISSUE TITLE
BUG: tpch-q4,16,20,22 query are not working with spice.ai connector

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#1987]
**Describe the bug**
        // Execution error: Unable to query Flight: Unable to query: status: InvalidArgument, message: \"Table 'tpch.supplier' not found

**To Reproduce**
run `cargo bench -p runtime` after enable tpch-q16 query.

All of these queries fail with the same issue that is rooted in spice.ai query engine.

**Comment by phillipleblanc** [comment]
Issue with an external service, not with the runtime. Closing.
