### ISSUE TITLE
Enhancement: Native schema inference for Data Connectors

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#2147]
## Goal-State/What/Result

Each Data Connector uses the source's native mechanism to retrieve the table schema.

## Why/Purpose

The current approach most data connectors have taken is to do a `SELECT * FROM {table} LIMIT 1` and infer the schema from the returned results. As #2061 has demonstrated, this cannot be relied upon.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** Oct 18

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

Basic specification of the enhancement.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- [x] #2460
- [x] #2461
- [x] #2462
- [x] #2463
- [x] #2464
- [x] #2465

**Comment by Sevenannn** [comment]
Target EOW: Done-done

**Comment by phillipleblanc** [comment]
Target EOW: Done-Done

**Comment by phillipleblanc** [comment]
This is done!
