### ISSUE TITLE
Enhancement: Federated Accelerated Tables for DuckDB

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#2182]
## Goal-State/What/Result

For duckdb accelerator, accelerated tables have federation push-down enabled. Accelerated tables that accelerate into the same file/DB instance have federation join push down enabled.

## Why/Purpose

Tables which are accelerated do not get the benefits of federation push down to reduce the computation done in DataFusion. This is especially apparent when accelerating tables into an accelerator duckdb engine file mode. This negatively impacts the performance of accelerated tables.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

Basic specification of the enhancement.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- [x] federation in a single duckdb acceleration table
- [x] #2313
- [x] Document
- [x] toggle to disable the federation on acceleration

**Comment by lukekim** [comment]
- @Sevenannn re-purpose this issue for common type conversion across accelerators.
- @peasee split into intra and inter DB federation for SQLite.
- @Sevenannn split into intra and inter DB federation for PostgreSQL.
- @y-f-u split into intra and inter DB federation for DuckDB.

**Comment by y-f-u** [comment]
@Sevenannn rewrote the common type conversion into #2285 . I am repurposing this for duckdb federated accelerated tables.

**Comment by y-f-u** [comment]
Inter table is pending on the sqlite change of attach/init.

**Comment by y-f-u** [comment]
actually federation is done. Follow-up regressions are raise, so close this in favour of those.

**Comment by peasee** [comment]
This is done-done with regressions
