### ISSUE TITLE
Enhancement: SQLite Acceleration Beta Hardening

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2204]
## Goal-State/What/Result

Through Spice, be able to accelerate up to 20GB of data into in-memory SQLite, or 200GB of data into file based mode.

## Why/Purpose

To ensure that the SQLite acceleration engine meets the beta hardening criteria for acceleration engines.

## By When

**Issue/Spec written and reviewed:** August 5th, 2024
**Done-Done:** August 12th, 2024

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

Basic specification of the enhancement.

## Implementation (issues)

- [x] #1867 
- [x] #2227 
- [x] #2237
- [x] #2273 
- [x] #2279 
- [x] #2280
- [x] #2298

### Feature set complete

- [x] Streaming when accelerating/loading
- [x] https://github.com/datafusion-contrib/datafusion-table-providers/pull/88
- [x] On conflict behaviors - Drop/Upsert
- [x] File mode for SQLite
- [x] Common/core arrow data type supports: Null, all Int types, all Float types, Time32, Time64, Timestamp (with/without TZ), Date32, Date64, Duration, Interval, Binary/LargeBinary/FixedSizeBinary, Utf8/LargeUtf8, List/FixedSizeList/LargeList, Struct, Decimal128/Decimal256
- [x] No known major bugs/issues
    - [x] https://github.com/spiceai/spiceai/issues/2555
    - [x] https://github.com/spiceai/spiceai/issues/2638

### Test Coverage

- [x] End-to-end test to cover accelerating TPCH-SF1 data from S3 and benchmarking TPCH queries (official and simple).
- [x] Integration tests to cover accelerating data from S3 parquet, MySQL, Postgres with arrow types: Null, all Int types, all Float types, Time32, Time64, Timestamp (with/without TZ), Date32, Date64, Duration, Interval, Binary/LargeBinary/FixedSizeBinary, Utf8/LargeUtf8, List/FixedSizeList/LargeList, Struct, Decimal128/Decimal256
- [x] Integration tests to cover "On Conflict" behaviors.
- [x] A reproducible test script that can load a variety of datasets into accelerators in both file/memory mode.
    - [x] Script can load TPCH-SF10
    - [x] Script can load TPCH-SF100
    - [x] Clickbench (from datafusion benchmark)

- [x] Load SF10 into SQLite acceleration in-memory
- [x] Load SF100 into SQLite acceleration on file
- [x] Query on SF10 dataset with memory mode
- [x] Query on SF100 dataset with file mode

### Docs

- [x] Doc/Specification include all required information from a user to set up the acceleration.
- [x] Include all known issues/limitations
- [x] Easy to follow quickstart (https://github.com/spiceai/quickstarts/pull/173)

### Data loading robustness

- [x] ~TPCH SF100 loaded into file, returned results are identical across source/federated/accelerated queries for all 21 TPCH queries and TPC simple queries. ~ Agreed to run sanity queries only. Full TPC-H pass is done on SF1 only.

### Functional queries

- [x] TPCH Queries can run on SF10 data in memory mode
- [x] TPCH Queries can run on SF100 data in file mode

**Comment by lukekim** [comment]
@peasee please update issue with new end date, create two new issues for SQLite Federation Within-Table federation and for across DB federation.

**Comment by phillipleblanc** [comment]
Target Outcome: Done-Done for the release

**Comment by sgrebnov** [comment]
Target Outcome: Done-Done 09/10

Remaining work:
 - Fix https://github.com/spiceai/spiceai/issues/2555
 - SQLite Accelerator Quickstart: https://github.com/spiceai/quickstarts/pull/173

**Comment by sgrebnov** [comment]
Completed
