### ISSUE TITLE
Enhancement: PostgreSQL Acceleration hardening

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#2225]
## Goal-State/What

Through Spice, be able to accelerate up to 200GB of data into Postgres

## Why

To ensure that Postgres accelerator meets the beta hardening criteria and can be used to accelerate real workloads in production.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** August 5th, 2024
**Done-Done:** August 12th, 2024

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md) - Bring data and ML to your application
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [ ] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

### Feature set complete

- [x] Streaming when accelerating/loading
- [x] Index
- [x] On conflict behaviors - Drop/Upsert
- [x] File mode
- [x] Common/core arrow data type supports: Null, all Int types, all Float types, Time32, Time64, Timestamp (with/without TZ), Date32, Date64, Duration, Interval, Binary/LargeBinary/FixedSizeBinary, Utf8/LargeUtf8, List/FixedSizeList/LargeList, Struct, Decimal128/Decimal256
- [x] No known major bugs/issues

### Test Coverage

- [x] End-to-end test to cover accelerating TPCH-SF1 data from S3 and benchmarking TPCH queries (official and simple).
- [x] Load SF10 into file
- [x]  Load SF100 into file
- [x] Integration tests to cover accelerating data from S3 parquet, MySQL, Postgres with arrow types: Null, all Int types, all Float types, Time32, Time64, Timestamp (with/without TZ), Date32, Date64, Duration, Interval, Binary/LargeBinary/FixedSizeBinary, Utf8/LargeUtf8, List/FixedSizeList/LargeList, Struct, Decimal128/Decimal256
  - [x] Null,
  - [x] All Int types, 
  - [x] All Float types, 
  - [x] Time32, 
  - [x] Time64, 
  - [x] Timestamp (with/without TZ), 
  - [x] Date32, Date64, 
  - [x] Duration, 
  - [x] Interval, 
  - [x] Binary/LargeBinary/FixedSizeBinary, 
  - [x] Utf8/LargeUtf8, 
  - [x] List/FixedSizeList/LargeList, 
  - [x] Struct, 
  - [x] Decimal128/Decimal256
- [x] Integration tests to cover "On Conflict" behaviors.
- [x] A reproducible test script that can load a variety of datasets into accelerators.
  - Can load below datasets
    - [x] TPCH-SF10
    - [x] TPCH-SF100
    - [x] TPCDS-SF10
    - [x] TPCDS-SF100
    - [x] ~db-benchmark join-datagen 50G~ (No longer part of beta hardening criteria)
    - [x] Clickbench (from datafusion benchmark)
    - [x] Semi-structure/Blob based data with row size 1M, 10M, 100M
  - Can run smoke test on accelerating
    - [x] ~Load SF100 into file~ (not applicable)
  - Can run smoke test on querying on accelerated data
    - [x] ~Query on SF100 dataset with file mode~ (not applicable, sanity queries will be run as part of `Can load TPCDS-SF100` task)
 
### Docs

- [x] Doc/Specification include all required information from a user to set up the acceleration.
- [x] Include all known issues/limitations
- [x] Easy to follow quickstart

### Data loading robustness

- [x] ~TPCH SF100 loaded into file, returned results are identical across source/federated/accelerated queries for all 21 TPCH queries and TPC simple queries. ~ Agreed to run sanity queries only. Full TPC-H pass is done on SF1 only.

### Functional queries

- [x] TPCH Queries can run on SF100 data (1-2 simple queries)

## How

If you already have an idea, a clear and concise description of how this should be implemented.

**Comment by phillipleblanc** [comment]
Target Outcome: Done-Done for release

**Comment by ewgenius** [comment]
@phillipleblanc to check with @Sevenannn on status

**Comment by phillipleblanc** [comment]
Blocked on DuckDB streaming for larger TPCH/TPCDS/Clickbench benchmarks. @phillipleblanc work on DuckDB streaming with highest priority.

@Sevenannn work on the Clickbench script for use in Postgres as well as other accelerators (SQLite, DuckDB).

**Comment by Sevenannn** [comment]
Close Postgres beta hardening as all hardening tasks are finished. A separate enhancement will be created for supporting all tpcds & Clickbench workloads in Postgres. Postgres federation will be disabled before tpcds workload support is completed
