### ISSUE TITLE
Enhancement: DuckDB Acceleration Beta Hardening

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#2235]
## Goal-State/What

Through Spice, Accelerate up to 20GB of data to in-memory duckdb, or 200GB of data in file based mode from any data connector.

## Why

To Demonstrate that Spice can be used to accelerate real workloads in production.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** Aug 8 2024
**Done-Done:** Aug 12 2024

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

### Feature set complete

- [x] Streaming when accelerating/loading
- [x] Index
- [x] On conflict behaviors - Drop/Upsert
- [x] File mode
- [x] Common/core arrow data type supports: Null, all Int types, all Float types, Time32, Time64, Timestamp (with/without TZ), Date32, Date64, Duration, Interval, Binary/LargeBinary/FixedSizeBinary, Utf8/LargeUtf8, List/FixedSizeList/LargeList, Struct, Decimal128/~~Decimal256 (documented)~~
- [x] No known major bugs/issues
    - https://github.com/spiceai/spiceai/issues/1870

### Test Coverage

- [x] End-to-end test to cover accelerating TPCH-SF1 data from S3 and benchmarking TPCH queries (official and simple).
  - file and memory modes
- [x] Integration tests to cover accelerating data from S3 parquet, MySQL, Postgres with arrow types: Null, all Int types, all Float types, Time32, Time64, Timestamp (with/without TZ), Date32, Date64, Duration, Interval, Binary/LargeBinary/FixedSizeBinary, Utf8/LargeUtf8, List/FixedSizeList/LargeList, Struct, Decimal128/~~Decimal256~~
- [x] #2357
- [x] A reproducible test script that can load a variety of datasets into accelerators in both file/memory mode.
  - Can load below datasets
    - [x] TPCH-SF10
    - [x] TPCH-SF100
    - [x] #2554
    - [x] #2607
    - [x] db-benchmark join-datagen 50G (from datafusion benchmark)
    - [x] clickbench_1 (from datafusion benchmark)
    - [x] ~~Semi-structure/Blob based data with row size 1M, 10M, 100M~~
  - Can run smoke test on accelerating
    - [x] Load SF10 into memory
    - [x] Load SF100 into file
  - Can run smoke test on querying on accelerated data
    - [x] Query on SF10 dataset with memory mode
    - [x] Query on SF100 dataset with file mode

### Docs

- [x] Doc/Specification include all required information from a user to set up the acceleration.
- [x] Include all known issues/limitations
- [x] Easy to follow quickstart

### Data loading robustness

- [x] TPCH SF10 loaded into memory, returned results are identical across source/federated/accelerated queries for all 21 TPCH queries and TPC simple queries.
- [x] TPCH SF100 loaded into file, returned results are identical across source/federated/accelerated queries for all 21 TPCH queries and TPC simple queries.

### Functional queries

- [x] TPCH Queries can run on SF10 data in memory mode
- [x] TPCH Queries can run on SF100 data in file mode

**Comment by y-f-u** [comment]
[accelerated.txt](https://github.com/user-attachments/files/16720390/accelerated.txt)
[federated.txt](https://github.com/user-attachments/files/16720391/federated.txt)

Queries return same result except the ones that might be mismatching due to order/limit issue.

**Comment by sgrebnov** [comment]
Outcome: done-done by next release.

Remaining: 
2. No results issue
3. TPCDS (loading and sanity tests)
4. Better error msg when accelerating to the same duckdb file (probably part of single instance improvement)
