### ISSUE TITLE
CLI: `spice sql` shift-enter should insert new line not execute the query

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#2260]
**Describe the bug**

Shift-enter should insert new line not execute the query.

**To Reproduce**
1. Run `spice sql`
2. Enter a query.
3. Edit the query and attempt to insert a new line using shift-enter.

**Expected behavior**
New line is inserted.

**Comment by eadgbear** [comment]
There's a limitation in `rustyline` that prevents this. Apparently on Unix systems SHIFT-ENTER and ENTER show up as the same character. I'm thinking that for now we scan for either a semicolon or an empty blank line at the end of input. So:

```sql
SELECT foo FROM
bar;
``` 
Will generate a query, as will:

```sql
SELECT foo FROM
bar
<blank>
```

**Comment by eadgbear** [comment]
One thing that's interesting to note is that a comparable experience is DuckDB, which *does* require a semicolon

**Comment by eadgbear** [comment]
Done
