### ISSUE TITLE
Add support for darwin/arm64

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#227]
See Apple's doc on tensorflow metal at https://developer.apple.com/metal/tensorflow-plugin/

- [ ] make macos-metal requirements/setup in AI engine (tensorflow-macos + tensorflow-metal)
- [ ] update contributing documentation
- [ ] make darwin/arm64 docker image (QEMU)
- [ ] setup github actions to support darwin/arm64 releases
- [ ] test darwin/arm64 support in CLI

**Comment by phillipleblanc** [comment]
Currently, this is failing because the Python libraries for grpc/protobuf are failing to import. There seems to be a workaround we can investigate.

Related issue:
https://github.com/grpc/grpc/issues/25082
