### ISSUE TITLE
Verbose mode for Spice CLI

### ISSUE THREAD

**Issue by edmondop** [spiceai/spiceai#2301]
I am trying to perform the followig command from the spiceAI [documentation](https://docs.spiceai.org/getting-started):

```sh
spice add spiceai/quickstart
Getting Spicepod spiceai/quickstart ...
an error occurred fetching Spicepod 'spiceai/quickstart'
```

However, the information is not sufficient to perform any troubleshoot. I suspect it might be a proxy problem, but I cannot really investigate it easily. I noticed that the CLI commands do not have a `-v` flag that can be used to enable more verbose logging, for example [here](https://github.com/spiceai/spiceai/blob/576d91cc28318d7d34626e00f438335f725785b1/bin/spice/pkg/registry/spicerack.go#L77)

**Comment by Jeadie** [comment]
For both `-v` and `-vv` flags to both `spice` and `spiced`.

For `spiced`, we will alter the `EnvFilter`. Will override environment variable `SPICED_LOG`.
 - `-v`: `task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG,WARN` 
 - `-vv`: `task_history=TRACE,spiced=TRACE,runtime=TRACE,secrets=TRACE,data_components=TRACE,cache=TRACE,extensions=TRACE,spice_cloud=TRACE,WARN` 

For `spice`, will only be used for `spice run` (pass through).

**Comment by Jeadie** [comment]
To increase verbosity of other `spice ...` commands, will require additional work to add underlying telemetry calls.

**Comment by Jeadie** [comment]
We decided on 
- `-v` -> `--verbose`
- `-vv` -> `--very-verbose`

**Comment by Jeadie** [comment]
This is now supported. We will need continued effort to improve the amount of logging at these lower levels
