### ISSUE TITLE
Can't get 'spice run'

### ISSUE THREAD

**Issue by NeverVane** [spiceai/spiceai#231]
Hi, I just followed the instruction but after running 
`spice run`

it downloads docker images and then fail into this error
`Error: Failed to verify health of localhost:8004 after 121 attempts exit status 1`

I'm running on 
- Ubuntu 18
- Docker 20.10.6, build 370c289

**Comment by lukekim** [comment]
Hi @NeverVane,

Thanks for reporting this! Would you grab us on Discord and we'll see if we can figure this out for you. https://discord.gg/PUCapX22En

**Comment by phillipleblanc** [comment]
It looks like this is an issue with Tensorflow requiring AVX instructions support (https://en.wikipedia.org/wiki/Advanced_Vector_Extensions) in the CPU. This issue in the Tensorflow repo explains it: https://github.com/tensorflow/tensorflow/issues/18322

We're planning to support multiple backends in the future (i.e. PyTorch) so hopefully we can work around this issue that way. You can follow this issue for updates on when we have support for multiple backends: https://github.com/spiceai/spiceai/issues/249

And in the meantime you can try using Spice.ai on a different machine and seeing that it works there. Thanks!
