### ISSUE TITLE
Enhancement: Models support for CLI

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#2311]
## Goal-State/What/Result

Models functionality can be used from CLI without a special build.

## Why/Purpose

Models functionality is read for preview.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

1. `install-cli-dev` functionality should be included by default.
2. Binaries with models are built and available in GH releases.
3. If model specific functions `spice chat` or `spice nsql` are used, the CLI will check for the appropriate runtime. If it is not installed, the user will be prompted to install.
4. `spice install ai` will manually install the models binaries.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- 
-

**Comment by phillipleblanc** [comment]
Added in #2374
