### ISSUE TITLE
Bug: SQLite does not support decimal Arrow types

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2320]

**Comment by Sevenannn** [comment]
SQLite support maximum 16 precision, the following actions will be take to close this ticket
- [x] Create decimal128 / decimal256 test cases with less than 16 precision for SQLite 
- [ ] Document the sqlite decimal precision limit as a limitation inside the documentation. [Document SQLite limitation in decimal support](https://github.com/spiceai/docs/pull/364)
