### ISSUE TITLE
Bug: SQLite does not support interval Arrow types

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2321]

**Comment by Sevenannn** [comment]
I've confirmed that arrow_json currently don't have decoding support for Interval types. Private ArrayDecoder trait need to be implemented in arrow-rs to make SQLite interval support work. Here is the summarized plan / next steps for supporting interval in SQLite.

- Document interval as a transient limitation in SQLite accelerator.
- Implement the interval decoder in my own / spiceai arrow-rs fork, and send PR to arrow-rs to enable the interval decoding functionality

Judgement call also need to be made regarding whether Interval should be supported through string SQLite accelerator. SQLite don't have a native interval type, the "string" interval won't be able to be used for any temporal computation / math through SQLite accelerator, which could be a common use case when it comes to using interval data.

**Comment by Sevenannn** [comment]
Documented as limitation in: https://docs.spiceai.org/components/data-accelerators/sqlite
