### ISSUE TITLE
DuckDB Accelerator is failing on TPCH Query4 & Query 22

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#2346]
DuckDB Accelerator is failing on TPCH Q4 & Q22 in the benchmark test:
![image](https://github.com/user-attachments/assets/33a7e23f-677b-481c-ba70-92741087a559)

**Comment by peasee** [comment]
This might be related to #2350

**Comment by peasee** [comment]
https://github.com/datafusion-contrib/datafusion-table-providers/pull/75
