### ISSUE TITLE
Accelerator queries with date ranges in where clause return no columns

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2349]
Running TPCH Q3, this error `Query Error Unexpected number of columns. Expected: 4, Found: 0` seems to stem from the 
```
and o_orderdate < date '1995-03-15'
  and l_shipdate > date '1995-03-15'
```

date comparisons in the where clause. Removing them makes the query run and return results as expected

**Comment by sgrebnov** [comment]
Note: this should NOT be the case when federation is disabled

**Comment by sgrebnov** [comment]
PR has been sent: https://github.com/spiceai/datafusion/pull/27
