### ISSUE TITLE
QA: Comprehensive test coverage for spill-to-disk and re-hydration Accelerator scenarios

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#2476]
## Goal-State/What/Result

Rigorous test coverage that provides confidence in the matrix of spill-to-disk and re-hydration scenarios for DuckDB and SQLite accelerators.

## Why/Purpose

Using a persistent file for spill-to-disk and re-hydration is the most common configuration of Spice and should have very good test coverage to ensure there are no regressions.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] ~UX Review~ (not applicable)
- [x] Threat Model / Security Review
- [x] Tests
- [x] ~Documentation~ (not applicable)
- [x] ~Samples/Quickstarts/Tutorials~ (not applicable)
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

### Scenarios

- [x] DuckDB auto-create file restart with re-hydration
- [x] DuckDB specified file restart with re-hydration
- [x] SQLite auto-create file restart with re-hydration
- [x] SQLite specified file restart with re-hydration
- [x] Restart with re-hydration after updated acceleration/app configuration: Index / PK

## How/MAP

Implement restart with re-hydration integration test (repeat 3 times)
1. Retrieve the number of rows using a native `MySQL` connection to use as a baseline.
1. Start Spice, retrieve row count and loaded items after acceleration is completed, and compare with the baseline.
1. Restart the runtime and ensure the loaded items remain consistent immediately after the runtime is loaded.
1. Simulate federated dataset access issue after the runtime is restarted, ensure query result remain consistent.

Note: add test to restart app during refresh ?
Note: do we need multiple datasets (federated mode)?

### Implementation (issues)
- [x] #2640
- https://github.com/datafusion-contrib/datafusion-table-providers/pull/101
- https://github.com/spiceai/spiceai/pull/2658

**Comment by sgrebnov** [comment]
Target outcome: Done-done by next release (09/18)

**Comment by sgrebnov** [comment]
On track to complete in 0.18.0-beta milestone

Update: tests have been implemented, SQLite is done, DuckDB - investigating why local database is empty after refresh (not repro when using spice in CLI mode in release). Will report Bug Sunday PST if this is actually an issue.

**Comment by sgrebnov** [comment]
Reported the following bug: [Bug: DuckDB local database has no records after checkpoint (file mode)](https://github.com/spiceai/spiceai/issues/2663)
