### ISSUE TITLE
Enhancement: `/ready` API only reports 200 when initial dataset load is successful

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#2481]
## Goal-State/What/Result

`/ready` API only reports 200 when initial dataset/models load is successful.

## Why/Purpose

When running in production, the system (Kubernetes normally) needs to know when spice daemon is ready for requests, where ready includes 100% data integrity and consistency.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** 9/10/24
**Done-Done:** 9/10/24

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [ ] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials
- [ ] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- 
-

**Comment by sgrebnov** [comment]
Planned outcome for this week: done-done
