### ISSUE TITLE
Enhancement: Single instance of embedded accelerator for all accelerated datasets (SQLite, DuckDB)

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#2561]
## Goal-State/What/Result

All DB instances from the same accelerator engine that can be combined into the same instance, should be. 

## Why/Purpose

Reduces the memory usage of Spice by reducing the number of DB instances loaded for accelerations. Potentially improves accelerator performance by allowing joins to be pushed down natively. Unblocks in-memory joins across accelerated datasets.

## By When

A target date for done-done completion of the entire enhancement.

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [ ] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [ ] The Algorithm
- [ ] PM/Design Review
- [ ] UX Review
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials
- [ ] Release Notes

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

### Cases where the same instance isn't possible
- Datasets that are explicitly told to accelerate into different DB files can't share the same instance.
- In-memory instances cannot be the same instance as file-backed datasets.

## How/MAP

A clear and concise plan of how this should be implemented.

### Implementation (issues)

- [x] #2665
- [x] #2666

**Comment by phillipleblanc** [comment]
Should handle accelerating multiple tables to the same file

**Comment by sgrebnov** [comment]
Planned outcome: done-done
