### ISSUE TITLE
Bug: DuckDB local database has no records after checkpoint (file mode)

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#2663]
## Describe the bug

The following integration test can be used to reproduce the problem. Query returns zero records for DuckDB. SQLite works.

[Tests: add persisted data verification after checkpoint](https://github.com/spiceai/spiceai/pull/2664)

Note: if I use Spice runtime via CLI and terminate it right after refresh (kill app command) I don't see such issue, local database contains records.

**Comment by peasee** [comment]
Data is not persisting to file in general for the DuckDB file-mode accelerator. Regression introduced by https://github.com/spiceai/spiceai/commit/dba7508d9aaa2fe971d44d9d56d44a70a8b64a1d

**Comment by phillipleblanc** [comment]
Will be properly fixed by https://github.com/spiceai/spiceai/pull/2669 but to mitigate for release, will revert the regression in https://github.com/spiceai/spiceai/pull/2676

**Comment by sgrebnov** [comment]
Issue has been fixed
