### ISSUE TITLE
Enhancement: Microsoft SQL Server (MSSQL) Data Connector

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#2688]
## Goal-State/What/Result

I can use Spice to query and accelerate datasets stored on Microsoft SQL Server.

## Why/Purpose

There is a large community of MS SQL users attempting to integrate with Spice, but the lack of a dedicated connector and no support in the ODBC connector creates a significant barrier.

## By When

**Issue/Spec written and reviewed:** 09/19
**Done-Done:** 09/23
## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

### Definition

`mssql:` prefix is used to define MS SQL Server connector

```yaml
datasets:
  - from: mssql:saleslt.customer
    name: customer
    params: 
      mssql_connection_string: ${ secrets:MSSQL_CONNECTION_STRING }
```

### Auth / Configuration

Only `SQL Login` is supported. Other authentication methods such as `Windows Authentication` and `Microsoft Entra ID` are out of scope.

**mssql_connection_string** -  a complete ADO connection string, which could be copied from the MSSQL Server configuration page or manually constructed. `Windows Auth` and `Micrsooft Entra ID` are out of scope. 

**mssql_host** - the hostname or IP address of the Microsoft SQL Server instance. Required if there is no connection_string provided.
**mssql_port** - the host port of the Microsoft SQL Server instance. Optional. Default is `1433`
**mssql_username** - the username for SQL authentication.
**mssql_password** - the password associated with the specified SQL user
**mssql_database** - the name of the specific database to connect. 
**mssql_encrypt** -  whether encryption is required for the connection (true or false). Default is true. Connection string uses true/false
**mssql_trust_server_certificate** - determines whether the server certificate is trusted without validation when encryption is enabled. Default is false. Connection string uses true/false

Example connection string
>Server=tcp:server-host.database.windows.net,1433;Initial Catalog=mssqlcatalog;Persist Security Info=False;User ID={Login};Password={Password};Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;

Example connection UI from Azure Data Studio
![image](https://github.com/user-attachments/assets/0eb38881-7b08-4cac-8c93-b5d88e5d57bb)

### Other

No federation and federated push-downs support are on scope for alpha support (note: this will be fully supported out of the box with data acceleration enabled)

## How/MAP

Use [tiberius](https://crates.io/crates/tiberius) -  native Microsoft SQL Server (TDS) client for Rust.

- [x] #2736
- [x] #2737
- [x] #2770
- [x] #2771
- [x] Support for binary for MSSQL
- [x] Streaming support for MSSQL
- [x] E2E test for MSSQL
- [x] Documentation for MSSQL
- [x] Sample/quickstart for MSSQL

### Implementation (issues)

- 
-

**Comment by sgrebnov** [comment]
Enhancement is done
