### ISSUE TITLE
task: Runtime supports `x-spice-user-agent` header values for telemetry

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2714]
## What

The Runtime supports reading `x-spice-user-agent` header values from the HTTP and Flight API requests.

The Runtime should take these header values and transform them into telemetry dimensions for:
- `user-agent`: The originating SDK user agent (e.g. `gospice`, `spicepy`, etc). If malformed or an invalid value, defaults to the originating protocol (e.g. `HTTP`, `Flight`).
- `user-agent-version`: The SDK version supplied with the SDK agent. For example, a header value of `gospice 0.1.0 (Pop!_OS 22.04 LTS)` would have a `user-agent-version: 0.1.0`. Malformed or invalid values default to `unknown`.
- `user-agent-os`: The OS the SDK is running on. For example, a header value of `gospice 0.1.0 (Pop!_OS 22.04 LTS)` would have a `user-agent-os: Pop!_OS 22.04 LTS`

These dimensions would then be sent over flight to the OSS telemetry.

**Comment by lukekim** [comment]
Closing as duplicate to https://github.com/spiceai/spiceai/issues/3312
