### ISSUE TITLE
Bug: TPCDS error `Invalid argument error: Column 'am_pm_ratio' is declared as non-nullable but contains null values`

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#2960]
## Describe the bug

Run [TPC-DS Benchmark](https://github.com/spiceai/spiceai/tree/trunk/crates/runtime/benches/queries/tpcds) Q90

>Query Error Unable to convert record batch: Invalid argument error: Column 'am_pm_ratio' is declared as non-nullable but contains null values

**Comment by peasee** [comment]
This also affects MySQL

**Comment by sgrebnov** [comment]
Assigning to @peasee to track for MySQL

Postgres returns `Division by zere` which is expected/aligned with native query experience; also updated query to prevent this error for Postgres
https://github.com/spiceai/spiceai/pull/3094/files
