### ISSUE TITLE
Bug: TPCDS error `Referenced column "substr(reason.r_reason_desc,Int64(1),Int64(20))" not found`

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#2962]
## Describe the bug

Run [TPC-DS Benchmark](https://github.com/spiceai/spiceai/tree/trunk/crates/runtime/benches/queries/tpcds) Q85, Q79

>Query Error Unable to query arrow: Unable to get schema: Binder Error: Referenced column "substr(reason.r_reason_desc,Int64(1),Int64(20))" not found in FROM clause!

**Comment by peasee** [comment]
This bug also affects MySQL. In MySQL, it appears as a bug in the ORDER BY statement, because it's wrapping it in backticks and trying to use it as a literal column name:

```
ORDER BY `substr(reason.r_reason_desc,Int64(1),Int64(20))`
```

Which sounds like the same problem as Postgres.

**Comment by sgrebnov** [comment]
Pr with the fix has been sent: https://github.com/spiceai/datafusion/pull/41
