### ISSUE TITLE
Enhancement: Sample data tool

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#3008]
## Goal-State/What/Result

Sample data tool (e.g. `get_sample_data`) that fetches top-N and distinct values the result of `list_datasets` call.

## Why/Purpose

_Clear and concise answer to why this should be done now._

## By When

_A target date for done-done completion of the entire enhancement._

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

### LLM Tools
Three tools
```rust
pub enum ExploreTableMethod {
    DistinctColumns {
        limit: usize,
        cols: Vec<String>,
        tbl: TableReference,
    },
    RandomSample{
        limit: usize,
        tbl: TableReference,
    },
    TopNSample{
        limit: usize,
        order_by: String,
        tbl: TableReference,
    },
}
```

Tool Response
 - Output user-friendly formatted output table (UX of tables shown in  `spice  sql`). 

### HTTP API 
```
curl http://localhost:8090/v1/datasets/sample \
     -XPOST  -H 'Accept: <application/json | text/csv | text/plain> \
    - data 'ExploreTableMethod'
``` 
 - Response format dependent on `Accept`, similar as `/v1/sql`.

**Comment by Jeadie** [comment]
Outstanding PRs:
- [x] https://github.com/spiceai/spiceai/pull/3108 
- [x] https://github.com/spiceai/spiceai/pull/3105 
- [x] Documentation (update [available tools](https://docs.spiceai.org/features/ai-gateway/runtime_tools#available-tools)).

**Comment by Sevenannn** [comment]
Target EOW: Done-done

**Comment by Jeadie** [comment]
Docs from https://github.com/spiceai/docs/pull/562
