### ISSUE TITLE
Enhancement: Search integration tests in CI

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#3011]
## Goal-State/What/Result

Spice Search functionality is covered by integration tests.

## Why/Purpose

Ensuring that search functionality covered by integration tests is important to detect issues earlier and release with high confidence.

## By When

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

_Basic specification of the enhancement._

## How/Plan

_A clear and concise plan of how this should be implemented._

### Implementation (Sub Issues)

- [x] https://github.com/spiceai/spiceai/pull/3410
- [x] https://github.com/spiceai/spiceai/pull/3599
- [x] #3731

**Comment by peasee** [comment]
@sgrebnov run through checklist and close off

**Comment by sgrebnov** [comment]
Search is covered by both integration and E2E tests, remaining work item: extend existing tests to cover chunking definition.

**Comment by sgrebnov** [comment]
Status: to be fully completed 12/02

**Comment by sgrebnov** [comment]
Completed
