### ISSUE TITLE
Enhancement: Search benchmark/performance tests in CI

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#3012]
## Goal-State/What/Result

Benchmark tests are added for Spice embeddings creation and search functionality to ensure that Spice functionality matches industry standards (performance/quality) and to detect bugs and regressions earlier.
 - Automated benchmark tests covering performance and overall search quality (correctness) based on industry-recognized benchmarking
 - Dashboard displaying key performance metrics over time
 - Tests include OpenAI and HF (local) embeddings models

## Why/Purpose

1. Running industry-recognized benchmarking tests will add confidence in Spice as a reliable and performant solution for vector search, ensuring that Spice meets or exceeds established quality and performance standards.
1. Allows detecting issues earlier to release with high confidence, and move quickly.

## By When

**Issue/Spec written and reviewed:** 12/03
**Done-Done:** 12/09

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md): Align to industry standards
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

1. Benchmark tests are based on industry-recognized [MTEB benchmark](https://github.com/embeddings-benchmark/mteb) dataset (specific dataset to be selected later)

2. The following metrics are collected and available on dashboard for each benchmark run:  

  Configuration | Timestamp | Index Time | Latency(ms) | P95(ms) | RPS | Precision | SHA
  -- | -- |-- | -- | -- | -- | -- | --

  - Index Time - time to create initial embeddings for the dataset
  - Precision  -  corresponds to [MTEB Retrieval Evaluator](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/evaluation/evaluators/RetrievalEvaluator.py) so benchmark results could be compared with the leaderboard or the same dataset+model benchmark tests run locally

3. Initial benchmark configurations:
 - OpenAI text-embedding-3-small, DuckDB file acceleration
 - Huggingface, Arrow acceleration
 - Huggingface, DuckDB file acceleration
 - Huggingface, DuckDB file acceleration, with chunking enabled

4. Spice.ai OSS AI Benchmark dashboard
 - Status - table containing the following information per configuration: `Last run`, `Index Time`, `P95(ms)`, `RPS`, `Precision`
 - Performance (p95): time series with p95 latency per configuration over time
 - Performance (Initial Indexing): time series with initial indexing time per configuration over time
 - Precision: time series with evaluated search precision per configuration over time

## How/Plan

1. Select the appropriate MTEB benchmark dataset based on its popularity and the size of the corpus and test records. The target corpus should consist of approximately 1 million rows to ensure a robust performance evaluation while maintaining cost efficiency. The projected cost for generating embeddings for 1 million rows using OpenAI's API is $0.020 per 1M token, resulting in an estimated cost of ~$0.60 (30 tokens per row).
1. Implement new benchmark: 
 - use HF to download benchmark dataset and construct Spicepod using file data connector pointing to the downloaded dataset file
 - use `vector_search::VectorSearch` directly to perform search (alternatively http endpoint can be used) requests using multiple parallel threads (5)
1. Calculate benchmark metrics
1. Create `oss_search_benchmarks` SCP dataset and add step to write benchmark metrics
1. Create dashboard
1. Setup GH workflow to run tests manually and every Fri

### Implementation (Sub Issues)

- [x] Search benchmark: select target benchmarking dataset
- [x] #3768
- [x] #3769
- [x] #3797
- [x] #3798
- [x] #3799
- [x] #3800
- [x] #3801
- [x] #3802

### QA

- Sub Issue 1
- Sub Issue 2

**Comment by sgrebnov** [comment]
12/02: Target outcome for this week: done-done

**Comment by sgrebnov** [comment]
12/09 status: new ETA to complete Tue 12/10.
- benchmark is implemented
- remaining work: benchmark results writing, dashboard, enable in CI

**Comment by Sevenannn** [comment]
EOW Status: Done-Done Dec-10

**Comment by sgrebnov** [comment]
12/16: 

Planned EOW status: Done-Done (12/17)
 - Remaining work: Grafana Dashboard

**Comment by sgrebnov** [comment]
12/23 update:
 - Planned EOW status: Done-Done (12/27)
 - Remaining work: dataset write (under internal review), dashboard

**Comment by sgrebnov** [comment]
12/28 update:
 - PR with the Search Benchmark dashboard has been sent, the Enhancement can be closed as done once it is merged and deployed.
