### ISSUE TITLE
Accelerator Beta Release: SQLite

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#3028]
### Feature complete

- [x] Data is streamed when accelerating from source into this accelerator
- [x] Data is streamed when reading/performing queries from this accelerator
- [x] The accelerator supports primary keys and indexes
- [x] The accelerator supports full federation within a single dataset (e.g. `select * from my_dataset`)
- [x] The accelerator supports federation push down across multiple datasets within the same accelerator (e.g. `select * from first_dataset, second_dataset`)
- [x] The accelerator supports resolving on conflict behaviors (e.g. Drop/Upsert)
- [x] Embdedded accelerators support file-mode storage (e.g. SQLite, DuckDB)
- [x] [Core Arrow Data Types](../definitions.md) are supported
    - [x] Null
    - [x] Int/Float
    - [x] Time32/64
    - [x] Timestamp/TimestampTZ
    - [x] Date32/64
    - [x] Duration
    - [ ] Interval. ⚠️ Interval type is not supported by SQLite (documented)
    - [x] Binary/LargeBinary/FixedSizeBinary
    - [x] Utf8/LargeUtf8
    - [x] List/FixedSizeList/LargeList. ⚠️ Lists of main primitive types only: https://github.com/spiceai/datafusion-federation/commit/2cb333011ae704b0e808e168d489ad303ab8e428#diff-09e332e2c593c7d73a6bc97b2964ff61ab7304bb8a9bfd6e66cfa3ea131e7451R211
    - [x] Struct
    - [x] Decimal128/Decimal256
- [x] All known [Major Bugs](../definitions.md) are resolved

### Test Coverage

Beta quality accelerators should be able to run test packages derived from the following:

- [TPC-H](https://www.tpc.org/TPC-H/)
- [TPC-DS](https://www.tpc.org/TPC-DS/)
- [ClickBench](https://github.com/ClickHouse/ClickBench)

Indexes are not required for test coverage, but can be introduced if required for tests to pass (e.g. due to performance characteristics, etc).

#### General

- [x] Integration tests to cover accelerating data from S3 parquet, MySQL, Postgres with the [Core Arrow Data Types](../definitions.md)
  - Arrow Types: https://github.com/datafusion-contrib/datafusion-table-providers/blob/main/tests/sqlite/mod.rs#L106
  - S3: via TPC-H/TPC-DS benchmark tests
  - MySQL: E2E acceleration of all MySQL types: `test_quickstart_data_mysql`
  - Postgres: E2E acceleration of all Postgres types: `test_quickstart_data_postgres`
- [x] Integration tests to cover "On Conflict" behaviors: https://github.com/spiceai/spiceai/blob/f37e40a1e168e90b4d1cf25283afba96f65bebba/crates/runtime/tests/acceleration/on_conflict.rs#L35

#### TPC-H

- [x] End-to-end test to cover accelerating TPC-H SF1 data from S3 and benchmarking TPC-H queries (official and simple).
  - [x] All [Access Modes](../definitions.md) should run all queries with no [Major Bugs](../definitions.md).
- [x] A test script exists that can load TPC-H SF10 and TPC-H SF100 data into this accelerator in all [Access Modes](../definitions.md).
- [x] The accelerator can load TPC-H SF10 in all [Access Modes](../definitions.md), and can run all queries with no [Major Bugs](../definitions.md).
- [x] The accelerator can load TPC-H SF100 in either [file or database mode](../definitions.md), and can run all queries with no [Major Bugs](../definitions.md).

#### TPC-DS

- [x] End-to-end test to cover accelerating TPC-DS SF1 data from S3 and benchmarking TPC-DS queries (official and simple).
     - ⚠️ Except queries containing unsupported features: `ROLLUP`, `GROUPING`, `stddev`; limitations were documented
  - [x] All [Access Modes](../definitions.md) should run all queries with no [Major Bugs](../definitions.md).
- [x] A test script exists that can load TPC-DS SF10 and TPC-DS SF100 data into this accelerator in all [Access Modes](../definitions.md).
- [x] The accelerator can load TPC-DS SF10 in all [Access Modes](../definitions.md), and can run all queries with no [Major Bugs](../definitions.md).
  - ⚠️ Can load and run simple queries but complex queries are slow/can't complete them on this scale.
- [x] The accelerator can load TPC-DS SF100 in either [file or database mode](../definitions.md), and can run all queries with no [Major Bugs](../definitions.md). 
  - ⚠️ Can load and run simple queries but complex queries are slow/can't complete them on this scale.

#### ClickBench

- [x] A test script exists that can load ClickBench data into this accelerator in either [file or database mode](../definitions.md).
- [x] The accelerator can load ClickBench in either [file or database mode](../definitions.md), and all queries are attempted.
  - [x] All query failures should be logged as issues. No bug fixes are required for ClickBench:
      - Reported https://github.com/spiceai/spiceai/issues/3315

#### Data correctness

Due to SQLite performance limitations Data correctness tested using the following scale:
- [x] TPC-H SF 1
- [x] TPC-DS SF 0.01 (except queries containing unsupported features: `ROLLUP`, `GROUPING`, `stddev`; limitations were documented)

- [x] [skipped as SQLite doesn't support this workload natively] TPC-H SF10 loaded into memory, returned results are identical across source and accelerated queries for all TPC-H queries and TPC-H simple queries.
- [x] [skipped as SQLite doesn't support this workload natively] TPC-H SF100 loaded into [file or database mode](../definitions.md), returned results are identical across source and accelerated queries for all TPC-H queries and TPC-H simple queries.
- [x] [skipped as SQLite doesn't support this workload natively] TPC-DS SF10 loaded into memory, returned results are identical across source and accelerated queries for all TPC-DS queries and TPC-DS simple queries. 
- [x] [skipped as SQLite doesn't support this workload natively] TPC-DS SF100 loaded into [file or database mode](../definitions.md), returned results are identical across source and accelerated queries for all TPC-DS queries and TPC-DS simple queries.

### Documentation

- [x] Documentation includes all information and steps for a user to set up the accelerator.
- [x] Documentation includes all known issues/limitations for the accelerator.
- [x] Documentation includes any exceptions made to allow this accelerator to reach Beta quality (e.g. if a particular data type cannot be supported by the accelerator).
- [x] The accelerator has an easy to follow quickstart.
- [x] All [Minor Bugs](../definitions.md) for TPC-DS and TPC-H are raised as issues.
- [x] All ClickBench bugs are raised as issues.
- [x] The accelerator status is updated in the table of accelerators in [spiceai/docs](https://github.com/spiceai/docs). https://github.com/spiceai/docs/pull/578

**Comment by sgrebnov** [comment]
Target outcome: done-done by 10/21. 
Status as of 10/15: not started working on this.

**Comment by sgrebnov** [comment]
Target outcome: done-done by 10/28.
Status as of 10/20: not started working on this due to other priority work.

**Comment by sgrebnov** [comment]
Target outcome: done-done by 10/30 (Wed).
Status as of 10/27: run TPC-DS benchmark, there are 4 issues related to incorrect query result and 3 issues related to unrecognized keywords that needs to be addressed.

**Comment by sgrebnov** [comment]
Accelerator is Beta quality 🎉

**Comment by phillipleblanc** [comment]
@sgrebnov please update the release criteria https://github.com/spiceai/spiceai/blob/trunk/docs/criteria/accelerators/beta.md

**Comment by sgrebnov** [comment]
PR to update release criteria: https://github.com/spiceai/spiceai/pull/3365
