### ISSUE TITLE
Accelerator Beta Release: PostgreSQL

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#3029]
### Feature complete

- [x] Data is streamed when accelerating from source into this accelerator
- [x] Data is streamed when reading/performing queries from this accelerator
- [x] The accelerator supports primary keys and indexes: https://github.com/datafusion-contrib/datafusion-table-providers/blob/main/src/postgres.rs#L446
- [x] The accelerator supports full federation within a single dataset (e.g. `select * from my_dataset`): via [FederatedTableProvider](https://github.com/datafusion-contrib/datafusion-table-providers/blob/main/src/postgres.rs#L157)
- [x] The accelerator supports federation push down across multiple datasets within the same accelerator (e.g. `select * from first_dataset, second_dataset`): via [FederatedTableProvider](https://github.com/datafusion-contrib/datafusion-table-providers/blob/main/src/postgres.rs#L157)
- [x] The accelerator supports resolving on conflict behaviors (e.g. Drop/Upsert): https://github.com/datafusion-contrib/datafusion-table-providers/blob/main/src/postgres/write.rs#L159
- [x] ~Embdedded accelerators support file-mode storage (e.g. SQLite, DuckDB)~ not applicable
- [x] [Core Arrow Data Types](../definitions.md) are supported: https://github.com/datafusion-contrib/datafusion-table-providers/blob/main/tests/postgres/mod.rs#L128
- [x] All known [Major Bugs](../definitions.md) are resolved

### Test Coverage

Beta quality accelerators should be able to run test packages derived from the following:

- [TPC-H](https://www.tpc.org/TPC-H/)
- [TPC-DS](https://www.tpc.org/TPC-DS/)
- [ClickBench](https://github.com/ClickHouse/ClickBench)

Indexes are not required for test coverage, but can be introduced if required for tests to pass (e.g. due to performance characteristics, etc).

When referring to accelerator access modes, "all supported modes" identifies every possible way to use that accelerator. For example, for DuckDB this would be file and memory modes. For PostgreSQL, this would only be the direct database access mode.

#### General

- [x] Integration tests to cover accelerating data from S3 parquet, MySQL, Postgres with the [Core Arrow Data Types](../definitions.md)
  - Arrow Types: https://github.com/datafusion-contrib/datafusion-table-providers/blob/main/tests/postgres/mod.rs#L128
  - S3: via TPC-H/TPC-DS benchmark tests
  - MySQL: E2E acceleration of all MySQL types: https://github.com/spiceai/spiceai/pull/3110
- [x] Integration tests to cover "On Conflict" behaviors: https://github.com/spiceai/spiceai/blob/f37e40a1e168e90b4d1cf25283afba96f65bebba/crates/runtime/tests/acceleration/on_conflict.rs#L35

#### TPC-H

- [x] End-to-end test to cover accelerating TPC-H SF1 data from S3 and benchmarking TPC-H queries (official and simple).
  - [x] All supported modes should run all queries with no [Major Bugs](../definitions.md).
- [x] A test script exists that can load TPC-H SF10 and TPC-H SF100 data into this accelerator in all supported modes: https://github.com/spiceai/spiceai/tree/trunk/test/scripts
- [x] The accelerator can load TPC-H SF10 in all supported modes, and can run all queries with no [Major Bugs](../definitions.md).
- [x] The accelerator can load TPC-H SF100 in either file or direct database mode, and can run all queries with no [Major Bugs](../definitions.md).

#### TPC-DS

- [x] End-to-end test to cover accelerating TPC-DS SF1 data from S3 and benchmarking TPC-DS queries (official and simple).
  - [x] All supported modes should run all queries with no [Major Bugs](../definitions.md).
- [x] A test script exists that can load TPC-DS SF10 and TPC-DS SF100 data into this accelerator in all supported modes. https://github.com/spiceai/spiceai/tree/trunk/test/scripts
- [x] The accelerator can load TPC-DS SF10 in all supported modes, and can run all queries with no [Major Bugs](../definitions.md).
- [x] The accelerator can load TPC-DS SF100 in either file or direct database mode, and can run all queries with no [Major Bugs](../definitions.md).
- [x] - [x] All [Minor Bugs](../definitions.md) for TPC-DS and TPC-H are raised as issues.

#### ClickBench
https://github.com/spiceai/spiceai/tree/trunk/test/scripts/clickbench
- [x] A test script exists that can load ClickBench data into this accelerator in either file or direct database mode.
- [x] The accelerator can load ClickBench in either file or direct database mode, and all queries are attempted.
  - [x] All query failures should be logged as issues. No bug fixes are required for ClickBench

#### Data correctness
- [x] TPC-H SF10 loaded into memory, returned results are identical across source and accelerated queries for all TPC-H queries and TPC-H simple queries.
- [x] TPC-H SF100 loaded into file or direct database mode, returned results are identical across source and accelerated queries for all TPC-H queries and TPC-H simple queries.
- [x] TPC-DS SF10 loaded into memory, returned results are identical across source and accelerated queries for all TPC-DS queries and TPC-DS simple queries.
- [x] TPC-DS SF100 loaded into file or direct database mode, returned results are identical across source and accelerated queries for all TPC-DS queries and TPC-DS simple queries.

Note: there is the following issue reported for data correctness. Taking into account this is Datafusion issue (returns the same result) and specific to some complex UNION+Aggregation queries this should NOT block Postgres from Beta promotion
 - https://github.com/spiceai/spiceai/issues/3049 
 - https://github.com/spiceai/spiceai/issues/3055

### Documentation
https://docs.spiceai.org/components/data-accelerators/postgres
https://github.com/spiceai/docs/pull/546
- [x] Documentation includes all information and steps for a user to set up the accelerator.
- [x] Documentation includes all known issues/limitations for the accelerator.
- [x] Documentation includes any exceptions made to allow this accelerator to reach Beta quality (e.g. if a particular data type cannot be supported by the accelerator).
- [x] The accelerator has an easy to follow quickstart: https://github.com/spiceai/quickstarts/blob/trunk/postgres/accelerator/README.md

**Comment by sgrebnov** [comment]
- Target completion date: 10/15 (Tue)
- [x] Remaining work - document evidences for criteria (add links/more details)

**Comment by sgrebnov** [comment]
Completed
