### ISSUE TITLE
MySQL Table 'foo' from one of the SELECTs cannot be used in global ORDER clause

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#3077]
TPC-DS Q76, Q66, Q60, Q56, Q33

Query Error Execution error: Unable to query arrow: Server error: `ERROR 42000 (1250): Table 'foo' from one of the SELECTs cannot be used in global ORDER clause

**Comment by sgrebnov** [comment]
Should be fixed by https://github.com/spiceai/datafusion/pull/39

**Comment by peasee** [comment]
> Should be fixed by [spiceai/datafusion#39](https://github.com/spiceai/datafusion/pull/39)

can confirm, the fix has resolved these issues for MySQL. Thanks!
