### ISSUE TITLE
Enhancement: Add `abfs` to `spice login`

### ISSUE THREAD

**Issue by eadgbear** [spiceai/spiceai#3082]
\*REMEMBER, BE **SMART**!

S: Specific
M: Measurable
A: Achievable
R: Relevant
T: Time-Bound\*

## Goal-State/What/Result

A `spice login abfs --tenant-id <tenant-id> --client-id <client-id>` sub-command that performs a one-time interactive login for the Microsoft OAuth2.0. Stores the bearer token, tenant id and client id in environment secrets is implemented for ABFS connector.

An unified OAuth mechanism for fetching `bearer token` for Microsoft relevant connectors (sharepoint, abfs) is implemented. 

Sharepoint parameter `sharepoint_auth_code` is updated to `sharepoint_bearer_token`, and uses the `bearer token` for authentication instead of `authorization code`.

## Why/Purpose

Simplify user's authentication with Azure Blob FS in spice by providing unified user experience of interactive device login. 

Improve code reusability by provide a reusable OAuth component that can be shared across Microsoft relevant connector (Sharepoint, Object Store), and align with standard auth approach provided by MSAL.

## By When

**Issue/Spec written and reviewed:** 
**Done-Done:** 

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

The following should be added to the `spice` CLI, `tenant-id` and `client-id` flags are required parameters
* `spice login abfs --tenant-id <tenant-id> --client-id <client-id>`

| Parameter               | Description                              | Variable Name               |
| ----------------------- | ---------------------------------------- | --------------------------- |
| `--tenant-id`           | Microsoft organization tenant ID         | `SPICE_ABFS_TENANT_ID`     |
| `--client-id`           | Microsoft Azure AD application client ID | `SPICE_ABFS_CLIENT_ID`     |

* The bearer access token from one-time interactive login will be stored in `SPICE_ABFS_BEARER_TOKEN` variable in in environment secrets.

Sharepoint connector updated to include `sharepoint_bearer_token` parameter and remove `sharepoint_auth_code `. 

* Sharepoint login will follow `spice login sharepoint --tenant-id <tenant-id> --client-id <client-id>`, with `SPICE_SHAREPOINT_BEARER_TOKEN `, `SPICE_SHAREPOINT_BEARER_TOKEN `, `SPICE_SHAREPOINT_BEARER_TOKEN` stored in environment secret and used for graph client authentication

### First Principles Driven

Align to industry standards

### Algorithm

The `spice login abfs` and `spice login sharepoint` sub-command share the same utility for signing in Microsoft app and obtaining tokens, utilizing the standard approach provided by [Microsoft Authentication Library (MSAL) Go](https://github.com/AzureAD/microsoft-authentication-library-for-go)
- The [authorization utility written in Go in Spice](https://github.com/spiceai/spiceai/blob/118a5dfd15e1a1935b8dae700fc4814098962b7b/bin/spice/pkg/msal/msal.go#L34) need to be updated to fetch `access_token` instead of `auth_code`. As [Microsoft OAuth](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-auth-code-flow) is a 2 step process (fetch auth code -> fetch token), and token is a more widely used end result for authentication - Object store doesn't supports access to Azure Blob FS with auth_code, while Graph rs client can perform OAuth step 2 to fetch token with auth_code. This approach of fetching token also aligns with common practice of MSAL(Reference: [Go](https://github.com/AzureAD/microsoft-authentication-library-for-go)), and removed the need for a hardcoded localhost server as Redirect URI.
- Accordingly, Sharepoint client need to be updated to include `bearer token` as an parameter, and utilize `bearer token` to construct Graph Client. This also removes the hard coded redirect URI `localhost:8091` within the Sharepoint conenctor.

Other authentication approach to ABFS, including `abfs_access_key`, `abfs_bearer_token` are scoped out from the enhancement, since they are not relevant to the Microsoft OAuth2.0 interactive login.

To use the interactive login, Spice users will need to configure the **azure app** with Redirect URI `http://localhost`, configure `user_impersonation` permission to the **azure app**, and assign **user** with the data `read access` for the azure storage account

### Security

No security concerns for user input. There is no query input to sanitize or relative file paths to validate or sanitize. The auth method should be confined to only fetch token with resource required for specific connector.

## How/Plan

- Reimplement the OAuth utility to fetch bearer access token
- Update Sharepoint connector parameter spec and Graph Client Initialization method (auth_code => bearer token)
- Implement the CLI commands for ABFS connector
- Comprehensive testing on the new auth utility and ABFS command
- Update ABFS connector documentation to include login command and configuration requirement
- Update Sharepoint connector documentation to include updates to parameter, login command and configuration requirement

**Comment by Sevenannn** [comment]
Target EOW: Done-done
