### ISSUE TITLE
Filters are not pushed down through Federated joins

### ISSUE THREAD

**Issue by eadgbear** [spiceai/spiceai#3116]
## Describe the bug

When joining a Dremio dataset and a Postgres dataset, the filters are not pushed down through the plan to the underlying dataset, resulting in the full data being pulled into memory. Neither dataset are accelerated, and the issue goes away when the Dremio dataset is accelerated.

## To Reproduce

1. Have Dremio Datasets
2. Have Postgres Dataset
3. Join together with a filter that affects only the Dremio dataset
4. Note in plan that the filter doesn't get pushed down

## Expected behavior

Filter gets pushed down through the plan

### Spicepod

Add the relevant `spicepod.yml` section.

### Output of the `describe table`

Add any relevant `describe table` output here.

### Output of `explain query`

Add any relevant `explain query` output here.

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

**Comment by sgrebnov** [comment]
Fixed by https://github.com/spiceai/spiceai/pull/3183
