### ISSUE TITLE
Connector RC Release: S3

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#3125]
### All Connectors

These requirements are imposed on every connector, regardless of the selected features/tests in the above table.

- [x] [Core Arrow Data Types](../definitions.md) are supported
  - [x] See [arrow - parquet mapping](https://arrow.apache.org/docs/cpp/parquet.html#types)
- [x] For exceptions where a [Core Arrow Data Type](../definitions.md) is not supported, print a warning and ignore the column instead of crashing or failing the query.
  - [x] Tested with edge cases for [arrow - parquet](https://arrow.apache.org/docs/cpp/parquet.html#types) conversion, no crash / failing of the query is seen. (e.g. JSON BSON, UUID, FixedSized List)
  - [x] Tested with CSV containing different types data of the same column, no crash / failing of the query is seen.
  - [x] Tested with CSV containing special inputs (e.g. a column of emoji), it loads empty table into datafusion due to unsupported types, but no crash / failing of the query is seen.
- [x] All known [Major Bugs](../definitions.md) are resolved

#### Documentation

- [x] Documentation includes all information and steps for a user to set up the connector.
- [x] Documentation includes all known issues/limitations for the connector.
- [x] Documentation includes any exceptions made to allow this connector to reach RC quality (e.g. if a particular data type cannot be supported by the connector).
- [x] The connector has an easy to follow quickstart.

#### Testing

- [x] Integration tests to cover simple use cases based on the connector type, e.g. a Spicepod sourcing a file from an FTP server, reading latest GitHub issues, etc.

### Conditional Criteria

The following features/tests are dependent on the required features/tests for the specified connector, from the [Connector criteria table](#rc-release-criteria)

#### Streaming

- [x] Data is streamed when reading/performing queries from this connector.

#### Schema Inference

Support for schema inference in a connector is classified as:

- ✅: Full coverage. The connector supports native schema inference.
- ⚠️: Partial coverage. The connector does not support native schema inference, but it requires no inference (e.g. static schema, etc).
- ❌: No coverage. The connector does not support native schema inference, and typically infers schema from the first row of results.

##### No Coverage

- [x] The connector does not support native schema inference.

#### Federation

Support for federation in a connector is classified as:

- ✅: Full coverage. The connector supports full federation and query push down.
- ⚠️: Partial coverage. The connector supports partial federation and query push down.
- ❌: No coverage. The connector does not support federation or query push down.

##### Partial Coverage

- [x] The connector supports filter federation within a single dataset for common use case columns (e.g. `select * from my_dataset where id = 1`)
  - Common use case should be determined at the discretion of the DRI for the connector.
  - For example, the GitHub connector should support filter federation for the author, state and title of issues.

#### Test Coverage

Indexes are not required for test coverage, but can be introduced if required for tests to pass (e.g. due to performance characteristics, etc).

##### TPC-H

- [x] End-to-end test to cover connecting to TPC-H SF1 for the connector type and benchmarking TPC-H queries (official and simple).
  - [x] Connectors should run all queries with no [Major Bugs](../definitions.md).
- [ ] ~A test script exists that can load TPC-H data at the [designated scale factor](#rc-release-criteria) into this connector.~
- [x] The connector can load TPC-H at the [designated scale factor](#rc-release-criteria), and can run all queries with no [Major Bugs](../definitions.md).
- [x] All [Minor Bugs](../definitions.md) for TPC-H are raised as issues.

##### TPC-DS

- [x] End-to-end test to cover connecting to TPC-H SF1 for the connector type and benchmarking TPC-DS queries (official and simple).
  - [x] Connectors should run all queries with no [Major Bugs](../definitions.md).
- [ ] ~A test script exists that can load TPC-DS data at the [designated scale factor](#rc-release-criteria) into this connector.~
- [x] The connector can load TPC-DS at the [designated scale factor](#rc-release-criteria), and can run all queries with no [Major Bugs](../definitions.md).
- [x] All [Minor Bugs](../definitions.md) for TPC-DS are raised as issues.

##### ClickBench

- [x] ~~A test script exists that can load ClickBench data into this connector at the [designated scale factor](#rc-release-criteria).~~ Not applicable for S3. Simple file upload.
- [x] All queries are attempted on this connector. No bug fixes are required for ClickBench.
- [x] All ClickBench bugs are raised as issues.

**Comment by phillipleblanc** [comment]
Target EOW: Done-Done
