### ISSUE TITLE
hive table support

### ISSUE THREAD

**Issue by oikomi** [spiceai/spiceai#3150]
Hello, is there a plan to support querying the hive table? 
In our business scenario, we need to process a large amount of hive table data, and we hope to get support.
Thank you!

**Comment by phillipleblanc** [comment]
@oikomi This support was added this week as part of #3086 and will be included in the next release. If you could build the latest trunk commit and test it out with your data, that would be helpful for us to validate it.

**Comment by oikomi** [comment]
> [@oikomi](https://github.com/oikomi) This support was added this week as part of [#3086](https://github.com/spiceai/spiceai/pull/3086) and will be included in the next release. If you could build the latest trunk commit and test it out with your data, that would be helpful for us to validate it.

Thank you very much, I will submit some tests as soon as possible

**Comment by phillipleblanc** [comment]
I needed to disable the hive support by default, you will need to add the following parameter (`hive_infer_partitions`) to your dataset parameters to enable hive support:

```yaml
datasets:
  - from: s3://my-bucket/
     name: files
     params:
       hive_infer_partitions: true
```

**Comment by oikomi** [comment]
hello,  Can hdfs be used as an address?

datasets:
  - from: **hdfs**://xxxx/xxx
     name: files
     params:
       hive_infer_partitions: true

**Comment by phillipleblanc** [comment]
No, we don't support HDFS. All of our available data connectors are listed in our docs: https://docs.spiceai.org/components/data-connectors

**Comment by phillipleblanc** [comment]
We renamed this parameter to `hive_partitioning_enabled `

**Comment by phillipleblanc** [comment]
This was implemented as part of https://github.com/spiceai/spiceai/releases/tag/v0.19.2-beta
Docs: https://docs.spiceai.org/components/data-connectors/s3#hive-partitioning-example
