### ISSUE TITLE
Datafusion builds incorrect subquery relation

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#3167]
## Describe the bug

This affects a number of connectors and accelerators, tested on MySQL and DuckDB. Seen in TPCDS Q49.

Datafusion builds a subquery using an incorrect alias. An example minimum reproduction is like:

```
SELECT j1_id FROM (SELECT ta.j1_id AS j1_id FROM j1 ta) -> SELECT ta.j1_id FROM (SELECT ta.j1_id FROM j1 AS ta)
```

Where Datafusion re-uses the `ta` table alias from inside the subquery that does not apply to the outer query. This results in an error that the table cannot be found, because the subquery has not been aliased as `ta`.

## To Reproduce

1. Configure TPCDS Q49 in DuckDB or MySQL
2. Run query
3. See error

## Expected behavior

The query should succeed.

### Output of `explain query`

TBA

### spice, spiced, OS info

- spice version: `v1.0.0-rc.1-rc.51f02f86`
- spiced version: `v1.0.0-rc.1-rc.51f02f86`

**Have you tried this on the latest `trunk` branch?**

- [x] Yes
- [ ] No

**Comment by sgrebnov** [comment]
@peasee - there were few recent increments in datafusion main related to subquery alias unparsing - worth to take a look
