### ISSUE TITLE
DuckDB ClickBench Q28 and Q29 fail for missing scalar `character_length`

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#3168]
## Describe the bug

DuckDB ClickBench Q28 and Q29 fail for missing scalar `character_length`

```
Query Error Execution error: Unable to query arrow: Unable to get schema: Catalog Error: Scalar Function with name character_length does not exist!
```

## To Reproduce

1. Configure ClickBench in DuckDB
2. Run ClickBench Q28 or Q29
3. See error

## Expected behavior

The query should succeed, or a workaround should be documented.

### Spicepod

Add the relevant `spicepod.yml` section.

### Output of the `describe table`

Add any relevant `describe table` output here.

### Output of `explain query`

Add any relevant `explain query` output here.

E.g. `explain select 1`

```bash
+---------------+--------------------------------------+
| plan_type     | plan                                 |
+---------------+--------------------------------------+
| logical_plan  | Projection: Int64(1)                 |
|               |   EmptyRelation                      |
| physical_plan | ProjectionExec: expr=[1 as Int64(1)] |
|               |   PlaceholderRowExec                 |
|               |                                      |
+---------------+--------------------------------------+
```

### spice, spiced, OS info

- spice version: `spice version`
- spiced version: `spiced --version`
- OS info: `uname -a`

**Have you tried this on the latest `trunk` branch?**

- [ ] Yes
- [ ] No

**If possible, run `spiced` with DEBUG log level**
By setting the environment variable `SPICED_LOG="task_history=DEBUG,spiced=DEBUG,runtime=DEBUG,secrets=DEBUG,data_components=DEBUG,cache=DEBUG,extensions=DEBUG,spice_cloud=DEBUG"`

**Comment by Sevenannn** [comment]
- Closed by: https://github.com/spiceai/datafusion/pull/59
