### ISSUE TITLE
Better error message when S3 client timeout is reached.

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#3224]
## Describe the bug

Currently the error message isn't very clear when the S3 client times out waiting for the data to be returned.

![Image](https://github.com/user-attachments/assets/b6fe9e79-2270-4c6c-8211-4544b5f451ce)

Fix the error message so its clear that the error is related to the client timed out waiting for a response from S3.

## To Reproduce

Create an S3 dataset with `client_timeout: 1s` 

`spice add spiceai/quickstart`

## Expected behavior

An error message that clearly explains the timeout, along with a suggested potential fix to increase the `client_timeout` parameter

**Comment by Sevenannn** [comment]
- Closed by: https://github.com/spiceai/arrow-rs/pull/1
