### ISSUE TITLE
Recommendation API not working with DQL algorithm

### ISSUE THREAD

**Issue by Corentin-pro** [spiceai/spiceai#325]
Tested on v0.2.1 with the `gardener` sample, the API does not respond.

**Comment by lukekim** [comment]
So far, could not reproduce with v0.3.0/v0.3.1. Will close, and can re-open if we see again.

![image](https://user-images.githubusercontent.com/80174/139237859-c12a85c5-7110-4b96-a026-fcfc128c959f.png)
