### ISSUE TITLE
Wrong algorithm name silently fails at training

### ISSUE THREAD

**Issue by Corentin-pro** [spiceai/spiceai#326]
Using the `--learning-algorithm` CLI parameter if the name is not either `vpg` or `dql` the training will say it is starting but will silently fail.

Reference: https://docs.spiceai.org/deep-learning-ai/

Validation should be done server-side (in spiced), with the error being passed back to the CLI over the HTTP call.

**Comment by lukekim** [comment]
We should just fix this with accepting the algorithm properly from the CLI as a command-line argument, and validating the arguments instead of a env var.

**Comment by lukekim** [comment]
I'm going to re-open this, because while now we have error reporting the message is not very user-friendly, so we still need @sboorlagadda's PR.

**Comment by lukekim** [comment]
I tested this, and it's working as expected now.

![image](https://user-images.githubusercontent.com/80174/147299801-36a9c158-5454-48ab-bc4b-36f9c7128b37.png)
