### ISSUE TITLE
Enable user friendly selection of learning algorithm

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#327]
Today: User specifies with env var.

Change: Remove the environment variable completely and replace with Manifest/CLI/API args/params.

0. Default (nothing specified): Hardcoded to DQL.
1. First level user override - User can specify in the pod manifest through an addition to Pod params.

E.g. 
```yaml
params:
  learning_algorithm: DQL | VPG
```

2. Second level user override - User can specify either A) API or B) CLI command line arg.

A) API - specified per training run by `POST /train` with body param:

```json
{
   "learning-algorithm": "DQL",
}
```

B) CLI - specified with `--learning-algorithm`. E.g. `spice run --learning-algorithm`

**Validation**

Both CLI and Server side.

**UI/UX**

Should show algorithm used on training run page.

**Flight/training run result**

Should also specify the algorithm used in output object so the user can compare results.

**Testing**

- Update the e2e tests to remove env var and replace with specifying command-line argument or API call (whichever is appropriate).
- Update Python unit tests to remove env var and use parameter.

**Docs**

Update with documentation of the above.

**Comment by Corentin-pro** [comment]
OK, the new parameter will need to be pass in the `train` API too. I will add it as parameter in the body of the POST request.
