### ISSUE TITLE
Enhancement: Add metrics properties based on Client `User-Agent` strings

### ISSUE THREAD

**Issue by eadgbear** [spiceai/spiceai#3312]
\*REMEMBER, BE **SMART**!

S: Specific
M: Measurable
A: Achievable
R: Relevant
T: Time-Bound\*

## Goal-State/What/Result

Spice OSS reports more detailed telemetry by adding additional metrics properties based on the `User-Agent` strings of clients.

If the `User-Agent` string matches a standardized form, additional labels will be generated.

## Why/Purpose

Aligning to Industry standards and surfacing usage information to the user. The ability to differentiate between different clients/runtimes to help diagnose performance or operational issues.

## By When

**Issue/Spec written and reviewed:** Wednesday, November 20th
**Done-Done:** 

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [ ] The Algorithm
- [ ] PM/Design Review
- [ ] DX/UX Review
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Performance / Benchmarks
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials
- [ ] Release Notes

## The Algorithm

- [ ] Every requirement questioned?
- [ ] Delete (Scope) any part you can.
- [ ] Simplify.
- [ ] Break down into smaller iterations/milestones.
- [ ] Opportunities for automation.

## Spec

- Client SDKs will provide a default standard User-Agent header, depending on the library and where the SDK is running: `User-Agent: gospice/0.20 (Darwin ...)`
- Direct runtime usage will have a way of constructing a custom `User-Agent` string

Multiple metric properties will be extracted from a User-Agent string of `spicebench/1.0 (Darwin) test_name/tpch_s3_q1`:
- `client`: e.g `spicebench`
-  `client_version`: e.g `1.0`
- `client_system`: e.g `Darwin`

- Metric properties will be derived only when client `User-Agent` strings match the expected pattern `<client>/<client_version> (<client_system>) key1/value1 key2/value2` 
    - `(client_system)` is optional
    - `key1/value1` is optional and translates to additional metric properties, one property per `key/value` pair
    - `key/value` pairs are deduplicated on `key` with the last one matching wins

- Interpret the `User-Agent` header in the Runtime and transform it to dimensions for `client`, `client_version`, and `client_system`. One additional metric property will be added for each Extension K/V pair
    * If `User-Agent` does not exist, default dimension values are passed
    * If `User-Agent` is malformed, default dimension values are passed
    * **Default dimension values**: `client: {originating protocol}`, `client_version: 1.0`, `client_system: (HTTP/gRPC)`

## How/Plan

- User libraries will be enhanced to enable default and custom User-Agent strings
- User-Agent parsing code will extract metric labels from HTTP and Flight `User-Agent` headers
- Context will be added during Query execution to pass information from the API entry points down to where the metrics are updated
- Existing tests and benchmarks will be updated with custom `User-Agent` strings

**Comment by lukekim** [comment]
@slyons Needs a principled design approved.

**Comment by peasee** [comment]
Done-Done: 27th Nov
