### ISSUE TITLE
Bug: SQlite `no such function: character_length` error

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#3315]
## Describe the bug

Run ClickBench test query Q28:

```
SELECT "CounterID", AVG(length("URL")) AS l, COUNT(*) AS c FROM hits WHERE "URL" <> '' GROUP BY "CounterID" HAVING COUNT(*) > 100000 ORDER BY l DESC LIMIT 25;
```

Observer error:

>Query Error Execution error: Unable to query arrow: ConnectionError Rusqlite("no such function: character_length in SELECT `hits`.`CounterID`, avg(CAST(character_length(`hits`.`URL`) AS DOUBLE)) AS `l`, count(1) AS `c` FROM `hits` WHERE (`hits`.`URL` <> '') AND (`hits`.`URL` <> '') GROUP BY `hits`.`CounterID` HAVING (count(1) > 100000) ORDER BY `l` DESC NULLS FIRST LIMIT 25 at offset 36")
sql> SELECT REGEXP_REPLACE("Referer", '^https?://(?:www\.)?([^/]+)/.*$', '\1') AS k, AVG(length("Referer")) AS l, COUNT(*) AS c, MIN("Referer") FROM hits WHERE "Referer" <> '' GROUP BY k HAVING COUNT(*) > 100000 ORDER BY l DESC LIMIT 25;

SQLite equivalent for `REGEXP_REPLACE` is `LENGTH` => Unparsing logic needs to be improved.

**Comment by sgrebnov** [comment]
To fix: use `scalar_function_to_sql_overrides` to override `character_length` and unaprse as  `length`
https://github.com/apache/datafusion/pull/12744/files#diff-305e66c0cc21e69a7c113f9f404dce0ee7be8b45f923177893965ec64310a183R326

**Comment by Sevenannn** [comment]
- Closed by: https://github.com/spiceai/datafusion/pull/59
