### ISSUE TITLE
Enhancement: Data Connector Release Candidate: GraphQL

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#3348]
## Goal-State/What/Result

The GraphQL Data Connector meets or exceeds the [release candidate criteria](https://github.com/spiceai/spiceai/blob/trunk/docs/criteria/connectors/rc.md).

## Why/Purpose

Part of our stated Roadmap: https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md

## By When

_A target date for done-done completion of the entire enhancement._

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

### All Connectors

These requirements are imposed on every connector, regardless of the selected features/tests in the above table.

The RC release criteria expand on and require that all [Beta release criteria](./beta.md) continue to pass for the connector.

- [x] All [Beta release criteria](./beta.md) pass for this connector.
- [x] For exceptions where a [Core Connector Data Type](../definitions.md) is not supported, print a warning and ignore the column instead of crashing or failing the query.
- [x] All known [Major Bugs](../definitions.md) are resolved.

#### Documentation

Documentation criteria should be re-checked on every release, to ensure the documentation is still accurate for the connector.

- [x] Documentation includes all information and steps for a user to set up the connector.
- [x] Documentation includes any mappings from [Core Connector Data Types](../definitions.md) to [Core Arrow Data Types](../definitions.md) types.
- [x] Documentation includes all known issues/limitations for the connector.
- [x] Documentation includes any exceptions made to allow this connector to reach RC quality (e.g. if a particular data type cannot be supported by the connector).
- [x] The connector has an easy to follow quickstart.
- [x] The connector status is updated in the table of connectors in [spiceai/docs](https://github.com/spiceai/docs).

### Conditional Criteria

The following features/tests are dependent on the required features/tests for the specified connector, from the [Connector criteria table](#rc-release-criteria)

#### Schema Inference

Support for schema inference in a connector is classified as:

- ❌: No coverage. The connector does not support native schema inference, and typically infers schema from the first row of results.

##### No Coverage

- [x] The connector does not support native schema inference.

#### Federation

Support for federation in a connector is classified as:

- ❌: No coverage. The connector does not support federation or query push down.'

## Release Notes

**GraphQL Data Connector**: Has graduated from Beta to Release Candidate.

**Comment by sgrebnov** [comment]
Target outcome: done-done
