### ISSUE TITLE
Enhancement: Data Connector Release Candidate: Databricks DeltaLake

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#3349]
## Goal-State/What/Result

The Databricks DeltaLake Data Connector meets or exceeds the [release candidate criteria](https://github.com/spiceai/spiceai/blob/trunk/docs/criteria/connectors/rc.md).

## Why/Purpose

Part of our stated Roadmap: https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md

## By When

_A target date for done-done completion of the entire enhancement._

**Issue/Spec written and reviewed:** <Target Date>
**Done-Done:** <Target Date>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

### All Connectors

These requirements are imposed on every connector, regardless of the selected features/tests in the above table.

The RC release criteria expand on and require that all [Beta release criteria](./beta.md) continue to pass for the connector.

- [x] All [Beta release criteria](./beta.md) pass for this connector.
- [x] For exceptions where a [Core Connector Data Type](../definitions.md) is not supported, print a warning and ignore the column instead of crashing or failing the query.
- [x] All known [Major Bugs](../definitions.md) are resolved.

#### Documentation

Documentation criteria should be re-checked on every release, to ensure the documentation is still accurate for the connector.

- [x] Documentation includes all information and steps for a user to set up the connector.
- [x] Documentation includes any mappings from [Core Connector Data Types](../definitions.md) to [Core Arrow Data Types](../definitions.md) types.
- [x] Documentation includes all known issues/limitations for the connector.
- [x] Documentation includes any exceptions made to allow this connector to reach RC quality (e.g. if a particular data type cannot be supported by the connector).
- [x] The connector has an easy to follow quickstart.
- [x] The connector status is updated in the table of connectors in [spiceai/docs](https://github.com/spiceai/docs).

### Conditional Criteria

The following features/tests are dependent on the required features/tests for the specified connector, from the [Connector criteria table](#rc-release-criteria)

#### Streaming

- [x] Data is streamed when reading/performing queries from this connector.

#### Schema Inference

Support for schema inference in a connector is classified as:

- ✅: Full coverage. The connector supports native schema inference.
- ⚠️: Partial coverage. The connector does not support native schema inference, but it requires no inference (e.g. static schema, etc).
- ❌: No coverage. The connector does not support native schema inference, and typically infers schema from the first row of results.

##### Full Coverage

- [x] The schema for data returned from queries is determined using a native CLI/library method provided by the connector.

#### Federation

Support for federation in a connector is classified as:

- ✅: Full coverage. The connector supports full federation and query push down.
- ⚠️: Partial coverage. The connector supports partial federation and query push down.
- ❌: No coverage. The connector does not support federation or query push down.

##### Partial coverage

- [x] The connector supports partial federation and query push down. (Filter pushdown when reading from delta_lake table).

#### Test Coverage

Indexes are not required for test coverage, but can be introduced if required for tests to pass (e.g. due to performance characteristics, etc).

##### TPC-H

- [x] End-to-end test to cover connecting to TPC-H SF1 for the connector type and benchmarking TPC-H queries (official and simple).
  - [x] Connectors should run all queries with no [Major Bugs](../definitions.md).
- [ ] A test script exists that can load TPC-H data at the [designated scale factor](#rc-release-criteria) into this connector.
- [x] The connector can load TPC-H at the [designated scale factor](#rc-release-criteria), and can run all queries with no [Major Bugs](../definitions.md).
- [x] All [Minor Bugs](../definitions.md) for TPC-H are raised as issues.
- [x] TPC-H queries that execute successfully on Datafusion, should execute successfully on the connector.

##### TPC-DS

- [x] End-to-end test to cover connecting to TPC-H SF1 for the connector type and benchmarking TPC-DS queries (official and simple).
  - [x] Connectors should run all queries with no [Major Bugs](../definitions.md).
- [ ] A test script exists that can load TPC-DS data at the [designated scale factor](#rc-release-criteria) into this connector.
- [x] The connector can load TPC-DS at the [designated scale factor](#rc-release-criteria), and can run all queries with no [Major Bugs](../definitions.md).
- [x] All [Minor Bugs](../definitions.md) for TPC-DS are raised as issues.
- [x] TPC-DS queries that execute successfully on Datafusion, should execute successfully on the connector.

##### ClickBench

- [x] A test script exists that can load ClickBench data into this connector at the [designated scale factor](#rc-release-criteria).
- [x] All queries are attempted on this connector. No bug fixes are required for ClickBench.
- [x] All ClickBench bugs are raised as issues.

#### Data Correctness

Data correctness can only be validated where the connector has a native CLI to replicate identical results. For connectors that do not have a native CLI to generate identical results, skip these tests.

Connectors that are excluded from these tests does not indicate that data is incorrect - it indicates only that we do not perform _automated_ testing of data correctness.

- [x] TPC-H queries at the [designated scale factor](#rc-release-criteria) return identical results in Spice and the native connector CLI.
- [x] TPC-DS queries at the [designated scale factor](#rc-release-criteria) return identical results in Spice and the native connector CLI.

**Comment by sgrebnov** [comment]
target outcome: done (delta lake mode).

**Comment by Sevenannn** [comment]
Target EOW: Done done
