### ISSUE TITLE
Enhancement: Iceberg Data Connector

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#3353]
## Goal-State/What/Result

Spice supports reading Iceberg tables via the [Iceberg Catalog Connector](https://github.com/spiceai/spiceai/issues/3872).

## Why/Purpose

Iceberg support will be important to reach customers that currently have data in Iceberg tables.

## By When

**Issue/Spec written and reviewed:** Nov 12, 2024
**Done-Done:** Nov 22, 2024

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [ ] PM/Design Review
- [ ] DX/UX Review
- [ ] Threat Model / Security Review
- [ ] Tests
- [ ] Performance / Benchmarks
- [ ] Documentation
- [ ] Samples/Quickstarts/Tutorials
- [ ] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

Use `iceberg-rs` to load the table metadata returned by the Iceberg Catalog REST API and create the table provider.

## How/Plan

_A clear and concise plan of how this should be implemented._

### Implementation (Sub Issues)

- Sub Issue 1
- Sub Issue 2

### QA

- Sub Issue 1
- Sub Issue 2

**Comment by sgrebnov** [comment]
Not planned for this week

**Comment by Sevenannn** [comment]
Target EOW: Done by next week

**Comment by phillipleblanc** [comment]
This will be done as part of #3872
