### ISSUE TITLE
Enhancement: make postgres and mysql SSL option names consistent

### ISSUE THREAD

**Issue by a-ellison** [spiceai/spiceai#3366]
## What

The names of the SSL configuration options are inconsistent between postgres and mysql.

postgres:
![Image](https://github.com/user-attachments/assets/7702dc85-93dd-4e88-96d4-1c05a1352360)

mysql:
![Image](https://github.com/user-attachments/assets/94810bea-3e01-41de-b63a-e338d268cd1b)

## Why

This inconsistency can easily lead to confusion (e.g. if copy pasting the postgres config when writing the mysql config).

**Comment by phillipleblanc** [comment]
In general we adhere to the parameter names of the underlying sources.

For Postgres: https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-PROTECTION

![Image](https://github.com/user-attachments/assets/56be2821-eb65-4d57-a67c-fc5b57bce2b4)

For MySQL: https://dev.mysql.com/doc/refman/8.4/en/connection-options.html#option_general_ssl-mode

![Image](https://github.com/user-attachments/assets/b403af55-8f6a-4efc-ac22-54ef0d5c22a9)

This is also why the names of the parameters are different (`mysql_sslmode` vs `pg_sslmode`)
