### ISSUE TITLE
Enhancement: Add an option to return SQL query instead of query results in /v1/nsql

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#3393]
`/v1/nsql` always returns query results. In some cases (e.g. for code completion), it would be useful to have only a generated query.

**Comment by Jeadie** [comment]
This can, or similar, likely be achieved via a standard chat/completion where, if we know which dataset they are using, tell the LLM to sample before completing text to SQL (and with a hardcoded "system prompt" in the user message). For example:

```shell
curl http://127.0.0.1:8090/v1/chat/completions \
-H "Content-Type: application/json" \
-d '{
  "model": "nql",  "tool_choice": {"type": "function", "function": {"name": "table_schema"}},
  "messages": [
    {
      "role": "user",
      "content": ""Task: {task_description}. Instruction: Return only valid SQL code, nothing additional. Columns with capitals must be quoted. For tables with schemas and catalogs '"catalog"."schema"."table"' not '"catalog.schema.table"'."}
  ]}'
```
