### ISSUE TITLE
Bug: GitHub rate limit warning doesn't show the dataset

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#3475]
## Describe the bug

GitHub rate limit warning doesn't show the dataset.

## To Reproduce

Add several github datasets with high refresh rates so rate limit is hit.

## Expected behavior

Warning message notes the dataset name.

### spice, spiced, OS info

CLI version:     `v1.0.0-rc.1-build.d5acbb43`
Runtime version: `v1.0.0-rc.1-build.ad160b7b+models`
OS version: `24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:23 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6031 arm64`

**Have you tried this on the latest `trunk` branch?**

- [X] Yes
- [ ] No

## Screenshots

![Image](https://github.com/user-attachments/assets/4383f8cf-f8c0-4496-8c1b-8457360151e8)

**Comment by peasee** [comment]
This error behavior is not GitHub specific - data connector errors for `UnableToGetReadProvider` do not specify the dataset name, which affects every connector.

**Comment by peasee** [comment]
## UX Changes

`DataConnectorError` should be updated to include a reference to the source dataset/catalog that is initiating the data connector request. The error message should be updated like: `Unable to get read provider for the dataset {dataset_name} ({dataconnector}): {source}`

For example: `Unable to get read provider for the dataset spiceai.pulls (github): ...`.

This is in comparison to the existing error message: `Unable to get read provider for github: ...`.

This change makes the dataset or catalog name the primary focus of the error message, with the connector type being moved to a more informational position.

**Comment by peasee** [comment]
Superseded by https://github.com/spiceai/spiceai/issues/3506
