### ISSUE TITLE
Name of algorithm used in the dashboard training run

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#394]
When a training run is in-progress or has been completed, the name of the learning algorithm used is not displayed. If training with different algorithms, it would be useful to compare the results of one algorithm with the other, and for that, we need to know which algorithm was used.

<img width="1313" alt="Screen Shot 2021-11-03 at 10 23 04 AM" src="https://user-images.githubusercontent.com/879445/139990040-29afd505-ae0e-4926-88e4-334ee31b9fe3.png">

**Comment by Adm28** [comment]
I would like to give this a shot. Is this issue still up for grabs ?

**Comment by lukekim** [comment]
@Adm28 oh, I missed this. Actually, this is closed with #410
