### ISSUE TITLE
Error on getting a recommendation on v0.3 compatible quickstarts/tweet-recommendation

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#460]
Debug this. The issue is passing a negative value to np.exp() in the soft_max function. The input array is the result of model.predict().

Console output:

```bash
/workspaces/spiceai/ai/src/algorithms/dql/agent.py:34: RuntimeWarning: overflow encountered in exp
  exp_q_values = np.exp(q_values)
/workspaces/spiceai/ai/src/algorithms/dql/agent.py:35: RuntimeWarning: invalid value encountered in true_divide
  return exp_q_values / np.sum(exp_q_values)
```

Callstack:

![image](https://user-images.githubusercontent.com/80174/142839096-a5c9a026-849e-4d93-85dc-684dd673ec50.png)

Overflow line:

![image](https://user-images.githubusercontent.com/80174/142839151-ec4cf94c-d871-44b5-9c57-27c928be3d98.png)

Input/Output objects to `np.exp`:

![image](https://user-images.githubusercontent.com/80174/142839259-cf16815f-e76d-4b92-bec7-3e1fc9eb6884.png)

**Comment by phillipleblanc** [comment]
Repro steps (with v0.3 spice):

```bash
cd quickstarts/tweet-recommendation
spice add quickstarts/tweet-recommendation@0.2.0
spice run --context metal &
spice train tweet-recommendation
<wait for training to complete>
curl http://localhost:8000/api/v0.1/pods/tweet-recommendation/recommendation

json: unsupported value: NaN
```

**Comment by Corentin-pro** [comment]
The problem is you can't use exponential function on such high numbers, example on ipython:

```
In [1]: import numpy as np

In [2]: np.exp(np.array([8000]))
<ipython-input-2-2668d4e95ccf>:1: RuntimeWarning: overflow encountered in exp
  np.exp(np.array([8000]))
Out[2]: array([inf])
```

Softmax is a function that will 'normalize' the number so the sum equate to 1 like a probability distribution. We can just divide by the absolute max before to avoid any `inf` as the values will be bounded to [-1, 1] but the output will be way smoother:

```
In [1]: import numpy as np

In [2]: q_values = np.array([65.493, 80.358, 85.290, 139.617])

In [3]: np.exp(q_values) / np.sum(np.exp(q_values))
Out[3]: array([6.43214496e-33, 1.83714442e-26, 2.54732103e-24, 1.00000000e+00])

In [4]: q_values /= 100.0

In [5]: np.exp(q_values) / np.sum(np.exp(q_values))
Out[5]: array([0.18255742, 0.21181531, 0.22252395, 0.38310332])

In [6]: q_values
Out[6]: array([0.65493, 0.80358, 0.8529 , 1.39617])
```
