### ISSUE TITLE
Specify the required version of docker in the limitations section of the README

### ISSUE THREAD

**Issue by dmonllao** [spiceai/spiceai#559]
host-gateway was added in docker 20.10.0 apparently. Older versions of docker won't be able to run the spiceai container (confirmed in a linux system running 19.x)

The two possible approaches are:
- To require docker 20.10.0 for container-based deployments
- Support docker 19.x by replacing the reference to host-gateway by an alternative way to connect to the host
 
I am opening a pull request listing the docker version 20.10.x in the pre-existing limitations section. Feel free to ignore if you want to go the other way, docker 20.10.0 was released on 2021-10-25 (https://docs.docker.com/engine/release-notes/#201010) but unsure how well adopted it is.

**Comment by phillipleblanc** [comment]
We've just released a new version of the runtime that removes the Docker requirement.
