### ISSUE TITLE
Spice OSS v0.9-alpha endgame

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#808]
Date: 03/14/2024

DRI: @sgrebnov 
Docs DRI: @ewgenius 
QA DRI: @sgrebnov 

Tag `v0.9-alpha`; release `release-v0.9-alpha`

- [x] Ensure all outstanding `spiceai` feature PRs are merged @sgrebnov 
- [x] Merge Docs PRs
  - [x] Postgres docs update - @mitchdevenport 
  - [x] Flight SQL @phillipleblanc
  - [x] Parquet files on S3 - @y-f-u 
  - [x] observability/metrics - @Jeadie  
- [x] Full test pass and update if necessary over README.md (please get screenshots!) @digadeesh 
- [x] Full test pass and update if necessary over Docs (please get screenshots!) @ewgenius 
- [x] ~Full test pass and update if necessary over existing and new Samples (please get screenshots/videos!)~
- [x] ~Full test pass and update if necessary over existing and new Quickstarts (please get screenshots/videos!)~
- [x] ~Merge Registry PRs~
- [x] ~Merge Samples PRs~
- [x] ~Merge Quickstarts PRs~
- [x] Merge release notes @lukekim 
- [x] Update acknowledgements @ewgenius
- [x]  Similar to https://github.com/spiceai/docs/pull/104/files
- [x] ~Update data-components-contrib repo with latest tag and reference it in spiceai. See [Components contrib version update](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#components-contrib-version-update)~
- [x] Update version using documented process at [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update)
- [x] QA DRI sign-off @sgrebnov 
- [x] Docs DRI sign-off @ewgenius 
- [x] Create a new branch `release-v[semver]` and merge all relevant changes into it. @sgrebnov 
- [x] Release the new version by creating a draft release with the tag from the release branch. @sgrebnov 
- [x] Release any docs updates by creating a `v[semver]` tag. @ewgenius 
- [x] Final test pass on released binaries @sgrebnov 
- [x] Reddit announcement to [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord announcement to [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] For major releases, [blog.spiceai.org](https://blog.spiceai.org) announcement
- [x] Update `version.txt` to the next release version. @sgrebnov 
- [x] Update version to the next release version in Cargo.toml. @sgrebnov

## PR reference:
-
-

**Comment by sgrebnov** [comment]
Spice: https://github.com/spiceai/spiceai/releases/tag/v0.9-alpha
Docs: https://github.com/spiceai/docs/releases/tag/v0.9-alpha

Blog posts:
https://www.reddit.com/r/spiceai/comments/1bf3xbb/spice_v09alpha_is_now_available/
https://blog.spiceai.org/posts/2024/03/15/announcing-the-release-of-spice.ai-v0.9-alpha/
