### ISSUE TITLE
Tonic OutOfRange messagetolarge error

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#839]
**Describe the bug**
Crash due to message too large.

**To Reproduce**

1. Add `lukekim/demo` spicepod.
2. Run query:

```sql
SELECT *
FROM eth_recent_traces trace
JOIN eth_recent_transactions trans ON trace.transaction_hash = trans.hash
ORDER BY trans.block_number DESC
```

**Expected behavior**
No crash. Query completes.

**Screenshots**
![image](https://github.com/spiceai/spiceai/assets/80174/c55a8f00-5fdf-485b-a2e7-14b92b3759a9)

**Comment by y-f-u** [comment]
There could be an easy fix to increase the tonic encoder/decoder range; however I am not satisfied with the solution as it still will bump into issues when the query is big.

Also for this query, the returning body is too huge to print out efficiently, a paging like `psql` would be a good addition.

Will prepare a PR to address these things.

**Comment by lukekim** [comment]
Increase limit to get data *but* by default only print the first 500 lines to console.
