### ISSUE TITLE
Generating go acknowledgements broken

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#840]
**Describe the bug**

When running `make generate-acknowledgements` it wipes all go entries.

If running underlying `go-licenses csv` command it can't get spiceai/spiceai package version, and returns only internal dependency

```
go-licenses csv .
W0318 11:06:38.866266   86747 library.go:276] module github.com/spiceai/spiceai has empty version, defaults to HEAD. The license URL may be incorrect. Please verify!
github.com/spiceai/spiceai/bin/spice,https://github.com/spiceai/spiceai/blob/HEAD/LICENSE,Apache-2.0
```

When using ignore `go-licenses csv . --ignore github.com/spiceai` it returns empty result.

**To Reproduce**

- Run `make generate-acknowledgements`
- Observe that all items removed from go section in `acknowledgements.md` 
![CleanShot 2024-03-18 at 11 11 33@2x](https://github.com/spiceai/spiceai/assets/827338/60aad71c-6c15-4deb-9fdb-4ef5fb1c128b)

**Expected behavior**
At least it should reference cli OSS dependencies (spf13/cobra, yaml, etc)

**Additional context**
https://pkg.go.dev/github.com/spiceai/spiceai shows wrong version - v0.7.0

![CleanShot 2024-03-18 at 11 13 46@2x](https://github.com/spiceai/spiceai/assets/827338/4ccb978c-1701-49ce-aef2-f016a643c412)

**Comment by lukekim** [comment]
@ewgenius please validate and close if fixed.

**Comment by ewgenius** [comment]
Confirmed that this issue is specific to my local setup.
