### ISSUE TITLE
Bug: PostgreSQL DataConnector should support connecting to servers with TLS configured

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#868]
**Describe the bug**
Connecting to a PostgreSQL server with TLS configured does not work.

**To Reproduce**
Sign up for a PostgreSQL server from [Neon](neon.tech). Try to connect to it via the PostgreSQL Data Connector. Observe the time out issue that occurs when the connection cannot be made.

**Expected behavior**
The connection works.

We hard-code the NoTls option here: https://github.com/spiceai/spiceai/blob/trunk/crates/db_connection_pool/src/postgrespool.rs#L66

**Comment by mitchdevenport** [comment]
Spoke to @y-f-u who has agreed to take this forward
