### ISSUE TITLE
BUG: REPL takes a long time to print out a large query result 

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#874]
**Describe the bug**
When using REPL to retrieve a large query result, the stdout is continuously printing for ages.

**To Reproduce**
- `spice sql`
- `select * from a_real_large_dataset`

**Expected behavior**
The repl should provide a nice way to handle this kind of situation, like `psql` to give user options to do paging, etc option

**Comment by lukekim** [comment]
Will be fixed with #839
