### ISSUE TITLE
Unable to run Spice on Windows using native binaries

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#946]
**Describe the bug**

Unable to run Spice on Windows

```
c:\spice>spice.exe run
Spice.ai runtime starting...
The Spice.ai runtime has not yet been installed.
Checking for latest Spice runtime release...
no releases
```

**To Reproduce**

1. Download the latest Spice release binaries for Windows
2. Run Spice from cmd using `spice.exe run`
3. See error

```
c:\spice>spice.exe run
Spice.ai runtime starting...
The Spice.ai runtime has not yet been installed.
Checking for latest Spice runtime release...
no releases
```

**Expected behavior**
Spice runtime is installed and Spice is run

**Screenshots**
<img width="487" alt="image" src="https://github.com/spiceai/spiceai/assets/981580/7f7e381a-b946-4f20-bc72-169c5bc4bdf7">

**Additional context**
If I run `spiced.exe` manually then I see the following error
<img width="373" alt="image" src="https://github.com/spiceai/spiceai/assets/981580/1cafcf90-a75b-4d8e-b28e-4fea3404620f">

**Comment by phillipleblanc** [comment]
Duplicate of #882

**Comment by sgrebnov** [comment]
Closing as duplicate
