### ISSUE TITLE
Adding a dataset with dots needs to be quoted or it shows as not existing

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#957]
**Describe the bug**
Creating a dataset name with dots, i.e. `eth.recent_blocks` will create a dataset with that table name:

```bash
sql> show tables
+---------------+--------------------+-------------------+------------+
| table_catalog | table_schema       | table_name        | table_type |
+---------------+--------------------+-------------------+------------+
| datafusion    | public             | eth.recent_blocks | BASE TABLE |
| datafusion    | information_schema | tables            | VIEW       |
| datafusion    | information_schema | views             | VIEW       |
| datafusion    | information_schema | columns           | VIEW       |
| datafusion    | information_schema | df_settings       | VIEW       |
+---------------+--------------------+-------------------+------------+
```

But querying without quoting will return an error:

```bash
sql> select * from eth.recent_blocks limit 10
Error An internal error occurred while processing the query. Show technical details with '.error'
```

Querying with quotes will work correctly:

```bash
select * from "eth.recent_blocks" limit 10
```

**Expected behavior**
We should warn users when they try to create/load a dataset with a name that has dots.

**Comment by ewgenius** [comment]
@phillipleblanc do you mean only in cli command `spice dataset configure` or it should be logged in runtime logs?

**Comment by phillipleblanc** [comment]
Both

**Comment by ewgenius** [comment]
@phillipleblanc looks like that is not possible (probably after some changes in re-architecture) - data fusion doesn't allow to register table with dots in name, because it parses that as a datafusion catalog

![Image](https://github.com/spiceai/spiceai/assets/827338/d2882164-a4f5-4d94-a193-c8dc5add18a0)

**Comment by digadeesh** [comment]
@ewgenius can we fix the error message so the action the user needs to take is more clear?
