### ISSUE TITLE
Clickhouse Data Connector

### ISSUE THREAD

**Issue by azhard4int** [spiceai/spiceai#999]
**Is your feature request related to a problem? Please describe.**

We are using Clickhouse for data warehousing for our real time analytics solution, is there any plan to have a data connector for Clickhouse? Adding a native Clickhouse connector would help a lot spiceai users and for the visibility of this project.

**Comment by Jeadie** [comment]
A short-term way to connect clickhouse could be to configure your clickhouse to be postgres compatible, see [these docs](https://clickhouse.com/docs/en/interfaces/postgresql).

**Comment by digadeesh** [comment]
To be included in the v0.12.0-alpha release.

* #1168 
* #1193 
* #1198 
* #1201 
* #1202
